### ISSUE TITLE
Stacktrace improvements

### ISSUE THREAD

**Issue by pengweiqhca** [getsentry/sentry-dotnet#101]
https://www.ageofascent.com/2018/01/26/stack-trace-for-exceptions-in-dotnet-core-2.1/

**Comment by bruno-garcia** [comment]
That's in the box for .NET Core 2.1. There's nothing for us to do there.
Or are you suggesting something? :)

**Comment by bruno-garcia** [comment]
`Ben.Demystifier` is something to look at but from my first look it seems to only affect the `.ToString()` and we actually inspect the properties.

There's surely a need to improve `Stacktrace` though, that we can agree.

**Comment by pengweiqhca** [comment]
``` ps
install-package Ben.Demystifier
```
Replace [new StackTrace(exception, true)](https://github.com/getsentry/sentry-dotnet/blob/master/src/Sentry/Internal/SentryStackTraceFactory.cs#L32) as
``` C#
new EnhancedStackTrace(exception)
```

**Comment by StasPerekrestov** [comment]
Hey, is it possible to turn off exceptions' stacktrace processing?
I mean, instead of 
```
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.TaskAwaiter`1", in GetResult
  File "D:\MyProject\src\ApiControllers\ImagesController.cs", line 30, col 5, in Get
    Void MoveNext()
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__1`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Web.Http.Controllers.ApiControllerActionInvoker", in InvokeActionAsyncCore
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Web.Http.Filters.ActionFilterAttribute", in CallOnActionExecutedAsync
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Web.Http.Filters.ActionFilterAttribute", in CallOnActionExecutedAsync
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Web.Http.Filters.ActionFilterAttribute", in ExecuteActionFilterAsyncCore
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
```
have the original exceptions string representation:
```
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyProject.Integrations.SomeCompany.Endpoint.SomeCompanyEndpoint.<GetQuoteAsync>d__8.MoveNext() in D:\MyProjectSrc\Production\Sources\MyProject.Integrations.SomeCompany\Endpoint\SomeCompanyEndpoint.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyProject.Integrations.SomeCompany.QuoteGeneration.SomeCompanyQuoteGenerator.<GenerateQuoteAsync>d__10.MoveNext() in D:\MyProjectSrc\Production\Sources\MyProject.Integrations.SomeCompany\QuoteGeneration\SomeCompanyQuoteGenerator.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyProject.Integrations.SomeCompany.QuoteGeneration.SomeCompanyQuoteGenerator.<GenerateQuotesAsync>d__8.MoveNext() in 
```

There are some IDEs, that allow to parse and analyze stacktraces. Having the sentry-related format doesn't allow to use the mentioned IDE's features.

**Comment by bruno-garcia** [comment]
@StasPerekrestov We have code that reads the stack trace/frames information and populates [the `StackFrame` from Sentry protocol ](https://github.com/getsentry/sentry-dotnet-protocol/blob/6a2f1384ff8522180497fbc9cb951c0306f622bf/src/Sentry.Protocol/Exceptions/SentryStackFrame.cs).

https://github.com/getsentry/sentry-dotnet/blob/478328c37ea0454312b218001415b8695a4c185e/src/Sentry/Internal/SentryStackTraceFactory.cs#L88-L121



To display what the raw format displays would require not a change in this SDK but on Sentry itself.
Please raise a separate issue for that.

**Comment by bruno-garcia** [comment]
There's an offer now from @pengweiqhca 

Samples:
https://github.com/getsentry/sentry-dotnet/pull/201/files

For support, please each out to the fork that owns the package:
https://github.com/pengweiqhca/sentry-dotnet
