### ISSUE TITLE
Improve flush on init

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1071]
Currently we block only up to 1 second, and then cancel the task if it times out.

Ideally we'd wait up to timeout, but not cancel the task (just let it run to completion) if timeout happens.

We could consider default to 2 seconds (on mobile 1 is never enough).

```
06-19 18:49:04.265 29233 29266 I DOTNET  :   Error: Failed to send cached envelope: /data/user/0/io.sentry.samples.maui/files/.local/share/Sentry/132A73C90BBA506000857BC4BFC23E574F1551B5/__processing/1624142399_-2131_0821212d3e2442a6b65f150c0b0ca563_-1340391907.envelope, retrying after a delay.
06-19 18:49:04.265 29233 29266 I DOTNET  : Sys
06-19 18:49:04.265 29233 29266 I DOTNET  : tem.Threading.Tasks.TaskCanceledException: The operation was canceled.
06-19 18:49:04.265 29233 29266 I DOTNET  :  ---> System.ObjectDisposedException: Cannot access a disposed object.
06-19 18:49:04.265 29233 29266 I DOTNET  : Object name: 'SslStream'.
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|137_0(Except
06-19 18:49:04.265 29233 29266 I DOTNET  : ionDispatchInfo e)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Security.SslStream.ThrowIfExceptional()
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Security.SslStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at Syste
06-19 18:49:04.265 29233 29266 I DOTNET  : m.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    --- End of inner exception stack trace ---
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean asy
06-19 18:49:04.265 29233 29266 I DOTNET  : nc, CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Http.HttpConnectionPool.SendUsingHttp11Async(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Http.HttpConnectionPool.Determine
06-19 18:49:04.265 29233 29266 I DOTNET  : VersionAndSendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Http.HttpConnectionPool.SendAndProcessAltSvcAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth,
06-19 18:49:04.265 29233 29266 I DOTNET  : CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Http.RedirectHandler.SendAsync(HttpRequ
06-19 18:49:04.265 29233 29266 I DOTNET  : estMessage request, Boolean async, CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at Sentry.Internal.Http.GzipBufferedRequestBodyH
06-19 18:49:04.265 29233 29266 I DOTNET  : andler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at Sentry.Internal.Http.RetryAfterHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at System.Net.Http.HttpClient.<SendAsync>g__Core|83
06-19 18:49:04.265 29233 29266 I DOTNET  : _0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at Sentry.Internal.Http.HttpTransport.SendEnv
06-19 18:49:04.265 29233 29266 I DOTNET  : elopeAsync(Envelope envelope, CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at Sentry.Internal.Http.CachingTransport.ProcessCacheAsync(CancellationToken cancellationToken)
06-19 18:49:04.265 29233 29266 I DOTNET  :    at Sentry.Internal.Http.CachingTransport.ProcessCacheAsync(CancellationToken cancellati
06-19 18:49:04.265 29233 29266 I DOTNET  : onToken)
06-19 18:49:04.266 29233 29233 I DOTNET  :   Error: Flushing timed out.
```

Relates to #803

**Comment by bruno-garcia** [comment]
Rough thought: `Task.WhenAny(transportTask, timeout)`

Check which task returned (compare reference) to log out what was the outcome (did we timeout or did we complete?)

important thing is not to share the cancellation token between tasks. If the timeout is reached, we don't want the transport to cancel the HTTP request.
