### ISSUE TITLE
Request Body not being captured

### ISSUE THREAD

**Issue by michaelakin** [getsentry/sentry-dotnet#1156]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
.Net core 3.8.3

### Steps to Reproduce

1. Asked Sentry to catpure body

### Expected Result

Body would be captured

### Actual Result

Body is not being captured.
After applying Sentry Debug setting, I see the following error in my output window

```
Sentry.ISentryClient: Error: Failed to extract body.

System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.get_Position()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.get_Position()
   at Sentry.Extensibility.BaseRequestPayloadExtractor.ExtractPayload(IHttpRequest request) in /_/src/Sentry/Extensibility/BaseRequestPayloadExtractor.cs:line 28
   at Sentry.Extensibility.RequestBodyExtractionDispatcher.ExtractPayload(IHttpRequest request) in /_/src/Sentry/Extensibility/RequestBodyExtractionDispatcher.cs:line 57
   at Sentry.AspNetCore.ScopeExtensions.SetBody(Scope scope, HttpContext context, SentryAspNetCoreOptions options) in /_/src/Sentry.AspNetCore/ScopeExtensions.cs:line 160
   at Sentry.AspNetCore.ScopeExtensions.Populate(Scope scope, HttpContext context, SentryAspNetCoreOptions options) in /_/src/Sentry.AspNetCore/ScopeExtensions.cs:line 59
Sentry.ISentryClient: Error: Failed to extract body.
```

**Comment by bruno-garcia** [comment]
Looks like the request was already closed when the SDK tried to capture the error.
Was that error captured on a background thread?

**Comment by peterhirn** [comment]
I just figured this out and wanted to leave a solution here.

There are multiple problems with sending request body streams as attachments in ASP.NET

1. The ASP request body stream is not seekable by default, see https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequestrewindextensions.enablebuffering

```
context.Request.EnableBuffering()
```

2. Stream consumer (`JsonDocument.ParseAsync`, `StreamReader`) usually close the source stream when they are done
  - `StreamReader` has a `leaveOpen` option, see https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor
  - For all other consumers you need to wrap the source stream in a `NonClosingStream`, see https://gist.github.com/angelyordanov/8d5123d54d80c9db51e561ebc7a7aa90, original https://jonskeet.uk/csharp/miscutil/

```
let parse (stream: Stream) =
    async {
        use nonClosingStream = new Streams.NonClosing(stream)

        return!
            JsonDocument.ParseAsync nonClosingStream
            |> Async.AwaitTask
    }
```

3. You need to reset the stream position if it has been accessed before you create the attachment

```
context.Request.Body.Position <- 0L
```

Finally this will work: `scope.AddAttachment(context.Request.Body, "payload")`

I believe there is a bug when the stream doesn't contain a final newline, which I'm about to report.

**Comment by bruno-garcia** [comment]
Thanks for writing down, lets us know if there's anything else
