### ISSUE TITLE
CachedTransportBackgroundTaskAsync is cancelled if TaskCancelledException occured inside HttpClient SendAsync

### ISSUE THREAD

**Issue by ruslansavchuk** [getsentry/sentry-dotnet#1366]
ASP.NET core 5

Sentry Asp.Net core 3.10.0

### Steps to Reproduce

1. Send envelop from CachedTransport using HttpTransport to sentry server
2. Sentry server does not return any response in appropriate time-window (default timeout for HTTP client 100 seconds)
3. Http client thow TaskCancelledException because timeout

### Expected Result
CachedTransport handle exception and retry

### Actual Result

CachedTransport stop working because TaskCancelledException is OperationCancelledException 

```
catch (OperationCanceledException)
  {
      throw; // Avoid logging an error.
  }
```

Original exception stacktrace
```
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Sentry.Internal.Http.GzipBufferedRequestBodyHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/GzipBufferedRequestBodyHandler.cs:line 69
   at Sentry.Internal.Http.RetryAfterHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/RetryAfterHandler.cs:line 91
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Sentry.Internal.Http.HttpTransport.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/HttpTransport.cs:line 177
   at Sentry.Internal.Http.CachingTransport.ProcessCacheAsync(CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 170
   at Sentry.Internal.Http.CachingTransport.ProcessCacheAsync(CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 172
```

**Comment by bruno-garcia** [comment]
Thank you for raising. We identified this issue yesterday while reviewing #1352 
It should be addressed there

**Comment by mattjohnsonpint** [comment]
@ruslansavchuk  - does this still happen, or did the changes with #1352 resolve it for you?  Thanks.

**Comment by mattjohnsonpint** [comment]
Since this appears to be resolved, I am closing the issue.  Please let us know if it needs to be re-opened.  Thanks.
