### ISSUE TITLE
Exception Thrown in a Static Constructor Is Not Being Sent To Sentry

### ISSUE THREAD

**Issue by twinmind** [getsentry/sentry-dotnet#1379]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
sentry.dotnet@v3.8.1

### Steps to Reproduce

Exception thrown in a static constructor doesn't get enqueued.

For example, we have a class with a static constructor that throws exception
```csharp
public class Address
{
    static Address() 
    {
            var cultures = CultureInfo.GetCultures(CultureTypes.SpecificCultures)
                .Select(x => new RegionInfo("qwerty")) //this will throw
                .Where(x => x.DisplayName != "World").ToList();
    }
}
```

when exception is handled like this:
```csharp
try
{
   var a = new Address();
}
catch (Exception ex)
{
    Sentry.CaptureException(ex);
}
```
where `Sentry` is a wrapper class like this:

```csharp
public class Sentry 
{
    public static readonly SentryClient Instance;

    static Sentry() 
    {
           Instance = new SentryClient(new SentryOptions {
                    Environment = "development"
                    Debug = true,
                    DiagnosticLevel = SentryLevel.Debug,
                    DiagnosticLogger = new TraceDiagnosticLogger(SentryLevel.Debug),
                    ServerName = System.Environment.MachineName,
                    Dsn = ($"my-dsn")
            });
    }

    public static void CaptureException(Exception ex)
    {
        var sentryEvent = new SentryEvent(ex);
        Instance.CaptureEvent(sentryEvent);
    }
}
```

in diagnostics mode, here's the exception I see when `CaptureEvent` is called:
```
Info: Capturing event.
  Debug: Running processor on exception: The type initializer for 'testApp.Address' threw an exception.
The thread 0x20d0 has exited with code 0 (0x0).
  Debug: Creating SentryStackTrace. isCurrentStackTrace: False.
The thread 0x1cdc has exited with code 0 (0x0).
'w3wp.exe' (CLR v4.0.30319: /LM/W3SVC/2/ROOT-13-132836386776909184): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll'. 
The thread 0x1f48 has exited with code 0 (0x0).
The thread 0x2364 has exited with code 0 (0x0).
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
The thread 0x2a8 has exited with code 0 (0x0).
  Error: An error occurred when capturing the event a7b03ff9ef0c4f1187f6867df9ee8f19.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'testApp.Address' threw an exception. ---> System.ArgumentException: Culture name 'qwerty' is not supported.
Parameter name: name
   at System.Globalization.RegionInfo..ctor(String name)
   at testApp.Address.<>c.<.cctor>b__8_0(CultureInfo x) in \\Mac\Home\dev\testApp\Address.cs:line 43
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at testApp.Address..cctor() in \\Mac\Home\dev\testApp\Address.cs:line 42
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.RuntimeFieldHandle.GetValue(RtFieldInfo field, Object instance, RuntimeType fieldType, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.UnsafeGetValue(Object obj)
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at System.Diagnostics.EnhancedStackTrace.GetMethodDisplayString(MethodBase originMethod)
   at System.Diagnostics.EnhancedStackTrace.GetFrames(StackTrace stackTrace)
   at Sentry.Extensibility.SentryStackTraceFactory.<CreateFrames>d__5.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.<ReverseIterator>d__75`1.MoveNext()
   at Sentry.Extensibility.SentryStackTraceFactory.Create(StackTrace stackTrace, Boolean isCurrentStackTrace)
   at Sentry.Internal.MainExceptionProcessor.<CreateSentryException>d__9.MoveNext()
   at Sentry.Internal.MainExceptionProcessor.<CreateSentryException>d__9.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Sentry.Internal.MainExceptionProcessor.Process(Exception exception, SentryEvent sentryEvent)
   at Sentry.SentryClient.DoSendEvent(SentryEvent event, Scope scope)
   at Sentry.SentryClient.CaptureEvent(SentryEvent event, Scope scope)
```

### Expected Result

Event would be sent to Sentry.

### Actual Result

`CaptureEvent` is called but it hasn't thrown exceptions and Sentry event wasn't sent.

**Comment by bruno-garcia** [comment]
This seems to be caused by [`Ben.Demystifier`](https://github.com/benaadams/Ben.Demystifier/) trying to get type info to make a more legible stack trace.

A work around to unblock you is to opt-out of that stacktrace mode through:

https://github.com/getsentry/sentry-dotnet/blob/d4f4192f2bbf88d6639fd518a616b34e3bc59cdc/src/Sentry/SentryOptions.cs#L498

By setting it to: `Classic`

A potential fix would be [to `try/catch` here in Ben.Demystifier](https://github.com/benaadams/Ben.Demystifier/blob/0eaebeb2d0251e3af1c45cf81dec77b4012bf0f7/src/Ben.Demystifier/EnhancedStackTrace.Frames.cs#L122) and fallback to the original name in case it fails. I'm not sure @benadams will merge that change without some benchmarks as I'm afraid it might negatively affect performance.

Alternatively we can try/catch in the Sentry SDK and fallback to the stacktrace mode, but that would result in different grouping between events coming from the two stack trace modes.

**Comment by SimonCropp** [comment]
@twinmind what .net version are you using?

**Comment by SimonCropp** [comment]
so i threw a test into  Ben.Demystifier, but i cant reproduce the above issue

```
        [Fact]
        public void Foo()
        {
            var exception = Assert.Throws<TypeInitializationException>(() =>
            {
                var type = new Address();
            });
            var trace = new StackTrace(exception);
            foreach (var frame in trace.GetFrames())
            {
                var methodBase = frame.GetMethod();
            }
        }

        public class Address
        {
            static Address() 
            {
                var cultures = CultureInfo.GetCultures(CultureTypes.SpecificCultures)
                    .Select(x => new RegionInfo("qwerty")) //this will throw
                    .Where(x => x.DisplayName != "World").ToList();
            }
        }
```

Perhaps i have misunderstand the circumstances that should trigger it

@twinmind would it be possible to get a small solution that reproduces the issue.

Also could you try updating the sentry sdk to 3.12.1

**Comment by twinmind** [comment]
@SimonCropp I can reproduce the Sentry issue consistently if I create a console app solution (called it `TestSentryFullFramework`) with .NET Framework 4.7.2, with Sentry 3.12.1. My development machine is Windows 10 VM running on Parallels.

These are my C# files:

Program.cs
```csharp
using System;

namespace TestSentryFullFramework {
    class Program {
        static void Main(string[] args) {
            try {
                var a = new Address();
            } catch (Exception ex) {
                Monitor.CaptureException(ex);
            }
        }
    }
}
```

Address.cs
```csharp
using System.Globalization;
using System.Linq;

namespace TestSentryFullFramework {
    public class Address {
        static Address() {
            var cultures = CultureInfo.GetCultures(CultureTypes.SpecificCultures)
                .Select(x => new RegionInfo("qwerty")) //this will throw
                .Where(x => x.DisplayName != "World").ToList();
        }

        public static string Home { get; set; } = "Home";
    }
}
```

Monitor.cs
```csharp
using Sentry;
using Sentry.Infrastructure;
using System;

namespace TestSentryFullFramework {
    class Monitor {
        public static readonly SentryClient Instance;

        static Monitor() {
            Instance = new SentryClient(new SentryOptions {
                Environment = "development",
                Debug = true,
                DiagnosticLevel = SentryLevel.Debug,
                DiagnosticLogger = new TraceDiagnosticLogger(SentryLevel.Debug),
                ServerName = Environment.MachineName,
                Dsn = "my-dsn"
            });
        }

        public static void CaptureException(Exception ex) {
            var sentryEvent = new SentryEvent(ex);
            var eventId = Instance.CaptureEvent(sentryEvent);
        }
    }
}

```

if you put breakpoint on the next line after `var eventId = Instance.CaptureEvent(sentryEvent);` in `Monitor.cs`, you'll see an exception in Debug Output window in Visual Studio (you can switch logger to use console if you replace TraceDiagnosticLogger with ConsoleDiagnosticLogger). The stack trace will be similar to the one I posted in the description. The actual top level exception seems to be `System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'TestSentryFullFramework.Address' threw an exception.`.

I tried to reproduce this by adding latest Ben.Demystifier and calling `EnhancedStackTrace.GetFrames(stackTrace)` explicitly but exception isn't thrown in this case.

**Comment by SimonCropp** [comment]
fixing upstream in Ben.Demystifier: https://github.com/benaadams/Ben.Demystifier/pull/187

**Comment by SimonCropp** [comment]
@twinmind thanks for the awesome repro. this would not have been possible to solve without your help
