### ISSUE TITLE
Flaky `ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1386]
The test `ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested` became flaky. First time I see and this test is very old.

Happened on `net461` on Windows (.NET Framework)

https://github.com/getsentry/sentry-dotnet/runs/4508510948?check_suite_focus=true

```
Sentry.Tests.Internals.Http.CachingTransportTests.ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested [FAIL]
Error: Sentry.Tests.Internals.Http.CachingTransportTests.ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested: Assert.False() Failure
  Failed Sentry.Tests.Internals.Http.CachingTransportTests.ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested [131 ms]
  Error Message:
   Assert.False() Failure
Expected: False
Actual:   True
  Stack Trace:
     at Sentry.Tests.Internals.Http.CachingTransportTests.<ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested>d__3.MoveNext() in D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\Internals\Http\CachingTransportTests.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at Sentry.Tests.Internals.Http.CachingTransportTests.<ShouldNotLogOperationCanceledExceptionWhenIsCancellationRequested>d__3.MoveNext() in D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\Internals\Http\CachingTransportTests.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Standard Output Messages:
 [Debug]: Storing file D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\bin\Release\net461\5f255f2f-4c92-4ef1-9f71-63abcfa233b2\Sentry\E071FE7F4BE9BFA6EDB6089C375F386F4142AD01\1639411205_-7379_3579c7c3661646718773b1e20d3d6326_6922919.envelope.
     Exception: <none>
Warning: ]: Cache directory is empty.
     Exception: <none>
 [Debug]: Worker signal triggered: flushing cached envelopes.
     Exception: <none>
 [Debug]: Reading cached envelope: D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\bin\Release\net461\5f255f2f-4c92-4ef1-9f71-63abcfa233b2\Sentry\E071FE7F4BE9BFA6EDB6089C375F386F4142AD01\__processing\1639411205_-7379_3579c7c3661646718773b1e20d3d6326_6922919.envelope
     Exception: <none>
 [Debug]: Sending cached envelope: 3579c7c3661646718773b1e20d3d6326
     Exception: <none>
 [Debug]: Canceled sending cached envelope: System.OperationCanceledException: The operation was canceled.
    at NSubstitute.ExceptionExtensions.ExceptionExtensions.<>c__DisplayClass5_0.<ThrowsForAnyArgs>b__0(CallInfo ci)
    at NSubstitute.Core.ReturnValueFromFunc`1.ReturnFor(CallInfo info)
    at NSubstitute.Core.CallResults.TryGetResult(ICall call, Object& result)
    at NSubstitute.Routing.Handlers.ReturnConfiguredResultHandler.Handle(ICall call)
    at NSubstitute.Routing.Route.Handle(ICall call)
    at NSubstitute.Core.CallRouter.Route(ICall call)
    at NSubstitute.Proxies.CastleDynamicProxy.CastleForwardingInterceptor.Intercept(IInvocation invocation)
    at Castle.DynamicProxy.AbstractInvocation.Proceed()
    at NSubstitute.Proxies.CastleDynamicProxy.ProxyIdInterceptor.Intercept(IInvocation invocation)
    at Castle.DynamicProxy.AbstractInvocation.Proceed()
    at Castle.Proxies.ObjectProxy_17.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken)
    at Sentry.Internal.Http.CachingTransport.<InnerProcessCacheAsync>d__15.MoveNext() in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 215
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Sentry.Internal.Http.CachingTransport.<ProcessCacheAsync>d__14.MoveNext() in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 162, retrying after a delay.
     Exception: <none>
Error: ]: Exception in background worker of CachingTransport.
     Exception: System.OperationCanceledException: The operation was canceled.
    at NSubstitute.ExceptionExtensions.ExceptionExtensions.<>c__DisplayClass5_0.<ThrowsForAnyArgs>b__0(CallInfo ci)
    at NSubstitute.Core.ReturnValueFromFunc`1.ReturnFor(CallInfo info)
    at NSubstitute.Core.CallResults.TryGetResult(ICall call, Object& result)
    at NSubstitute.Routing.Handlers.ReturnConfiguredResultHandler.Handle(ICall call)
    at NSubstitute.Routing.Route.Handle(ICall call)
    at NSubstitute.Core.CallRouter.Route(ICall call)
    at NSubstitute.Proxies.CastleDynamicProxy.CastleForwardingInterceptor.Intercept(IInvocation invocation)
    at Castle.DynamicProxy.AbstractInvocation.Proceed()
    at NSubstitute.Proxies.CastleDynamicProxy.ProxyIdInterceptor.Intercept(IInvocation invocation)
    at Castle.DynamicProxy.AbstractInvocation.Proceed()
    at Castle.Proxies.ObjectProxy_17.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken)
    at Sentry.Internal.Http.CachingTransport.<InnerProcessCacheAsync>d__15.MoveNext() in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 215
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Sentry.Internal.Http.CachingTransport.<ProcessCacheAsync>d__14.MoveNext() in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 172
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Sentry.Internal.Http.CachingTransport.<CachedTransportBackgroundTaskAsync>d__11.MoveNext() in /_/src/Sentry/Internal/Http/CachingTransport.cs:line 85
 [Debug]: Background worker of CachingTransport has shutdown.
     Exception: <none>



Failed!  - Failed:     1, Passed:   950, Skipped:     3, Total:   954, Duration: 17 s - Sentry.Tests.dll (net461)
```

**Comment by bruno-garcia** [comment]
Happened also here: https://github.com/getsentry/sentry-dotnet/runs/4526660877?check_suite_focus=true

**Comment by bruno-garcia** [comment]
Again: https://github.com/getsentry/sentry-dotnet/runs/4541933197?check_suite_focus=true

**Comment by bruno-garcia** [comment]
Again: https://github.com/getsentry/sentry-dotnet/runs/4576337131?check_suite_focus=true

Pretty often now

**Comment by bruno-garcia** [comment]
Seems to fail only on Windows with .NET Framework
