### ISSUE TITLE
Flaky: `TryGetPersistentInstallationId_SessionStarted_ReturnsLastSession`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1457]
Error: 

```
Sentry.Tests.GlobalSessionManagerTests.TryGetPersistentInstallationId_SessionStarted_ReturnsLastSession: Expected persistedSessionUpdate!.Timestamp to be after <2022-02-03 20:50:13.4225165 +0h>, but it was <2022-02-03 20:50:13.4225165 +0h>.
  Failed Sentry.Tests.GlobalSessionManagerTests.TryGetPersistentInstallationId_SessionStarted_ReturnsLastSession [23 ms]
  Error Message:
   Expected persistedSessionUpdate!.Timestamp to be after <2022-02-03 20:50:13.4225165 +0h>, but it was <2022-02-03 20:50:13.4225165 +0h>.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.DateTimeOffsetAssertions`1.BeAfter(DateTimeOffset expected, String because, Object[] becauseArgs)
   at Sentry.Tests.GlobalSessionManagerTests.TryGetPersistentInstallationId_SessionStarted_ReturnsLastSession() in D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\GlobalSessionManagerTests.cs:line 313
```

**Comment by bruno-garcia** [comment]
Seems to be consistent actually: https://github.com/getsentry/sentry-dotnet/runs/5058294511?check_suite_focus=true

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry-dotnet/blob/7fa7986238ebd5a97ec2eeab359d4dcbd76dc9c2/test/Sentry.Tests/GlobalSessionManagerTests.cs#L291
