### ISSUE TITLE
Intermittent failure of Environment_OnOptions_ValueFromOptions 

### ISSUE THREAD

**Issue by SimonCropp** [getsentry/sentry-dotnet#1532]
```
NSubstitute.Exceptions.ReceivedCallsException: Expected to receive exactly 1 call matching:

NSubstitute.Exceptions.ReceivedCallsException
Expected to receive exactly 1 call matching:
	EnqueueEnvelope(e => (e.Items.Select(i => i.Payload).OfType().Select(i => i.Source).OfType().Single().Environment == "environment"))
Actually received 5 matching calls:
	EnqueueEnvelope(Envelope)
	EnqueueEnvelope(Envelope)
	EnqueueEnvelope(Envelope)
	EnqueueEnvelope(Envelope)
	EnqueueEnvelope(Envelope)

   at NSubstitute.Core.ReceivedCallsExceptionThrower.Throw(ICallSpecification callSpecification, IEnumerable`1 matchingCalls, IEnumerable`1 nonMatchingCalls, Quantity requiredQuantity)
   at NSubstitute.Routing.Handlers.CheckReceivedCallsHandler.Handle(ICall call)
   at NSubstitute.Routing.Route.Handle(ICall call)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleForwardingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy_20.EnqueueEnvelope(Envelope envelope)
   at Else.AspNetCore.Tests.IntegrationMockedBackgroundWorker.Environment_OnOptions_ValueFromOptions() in D:\Code\sentry-dotnet\test\Sentry.AspNetCore.Tests\IntegrationMockedBackgroundWorker.cs:line 282
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

```

**Comment by mattjohnsonpint** [comment]
Haven't seen this in awhile.  Closing for now.  Re-open if it comes back please.
