### ISSUE TITLE
 'System.PlatformNotSupportedException', reason: 'Operation is not supported on this platform. (System.PlatformNotSupportedException)

### ISSUE THREAD

**Issue by anpin** [getsentry/sentry-dotnet#1561]
Please mark the type framework used:

- [X] Other: net6.0-maccatalyst

Please mark the NuGet packages used:

- [X] Sentry
- [X] Sentry.Serilog
- [X] Sentry.Extensions.Logging

* Version: 3.15.0

Seems like Sentry doesn't yet support `net6.0-maccatalyst` target, app crashes on startup with 
(I also looked into supplying my own http factory, but property is internal)
```
Application Specific Information:
*** Terminating app due to uncaught exception 'System.PlatformNotSupportedException', reason: 'Operation is not supported on this platform. (System.PlatformNotSupportedException)
at System.Net.Http.NSUrlSessionHandler.get_SupportsAutomaticDecompression()
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
at System.Net.Http.HttpClientHandler.InvokeNativeHandlerMethod(String name, Object[] parameters)
at System.Net.Http.HttpClientHandler.GetSupportsAutomaticDecompression()
at System.Net.Http.HttpClientHandler.get_SupportsAutomaticDecompression()
at Sentry.Internal.Http.DefaultSentryHttpClientFactory.Create(SentryOptions options) in /_/src/Sentry/Internal/Http/DefaultSentryHttpClientFactory.cs:line 34
at Sentry.Internal.SdkComposer.CreateTransport() in /_/src/Sentry/Internal/SdkComposer.cs:line 37
at Sentry.Internal.SdkComposer.CreateBackgroundWorker() in /_/src/Sentry/Internal/SdkComposer.cs:line 112
at Sentry.SentryClient..ctor(SentryOptions options, IBackgroundWorker worker) in /_/src/Sentry/SentryClient.cs:line 52
at Sentry.SentryClient..ctor(SentryOptions options) in /_/src/Sentry/SentryClient.cs:line 39
at Sentry.Internal.Hub..ctor(SentryOptions options, ISentryClient client, ISessionManager sessionManager, ISystemClock clock, IInternalScopeManager scopeManager) in /_/src/Sentry/Internal/Hub.cs:line 51
at Sentry.SentrySdk.InitHub(SentryOptions options) in /_/src/Sentry/SentrySdk.cs:line 53
at Sentry.SentrySdk.Init(SentryOptions options) in /_/src/Sentry/SentrySdk.cs:line 97
at Serilog.SentrySinkExtensions.Sentry(LoggerSinkConfiguration loggerConfiguration, Action`1 configureOptions) in /_/src/Sentry.Serilog/SentrySinkExtensions.cs:line 341
```

**Comment by mattjohnsonpint** [comment]
This will be important for MAUI.  I'll take a look. Thanks for reporting!

**Comment by SimonCropp** [comment]
looking at the stack trace I suspect this is a bug in .net. @anpin given i am on windows, can you create a standalone `net6.0-maccatalyst`, and see if you can access `HttpClientHandler.SupportsAutomaticDecompression`

**Comment by anpin** [comment]
@SimonCropp indeed accessing `HttpClientHandler.SupportsAutomaticDecompression` on both `net6.0-ios` and `net6.0-maccatalyst` targets produces
```
'Operation is not supported on this platform. (System.PlatformNotSupportedException)
   at System.Net.Http.NSUrlSessionHandler.get_SupportsAutomaticDecompression()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpClientHandler.InvokeNativeHandlerMethod(String name, Object[] parameters)
   at System.Net.Http.HttpClientHandler.GetSupportsAutomaticDecompression()
   at System.Net.Http.HttpClientHandler.get_SupportsAutomaticDecompression()
```
![image](https://user-images.githubusercontent.com/6060545/161519085-f6457923-27a4-40df-b25c-4dcdc77909a2.png)

**Comment by anpin** [comment]
Work fine on `net6.0-android` and `net6.0-windows` repro is [here ](https://github.com/anpin/MauiHttphandlerRepro)
![image](https://user-images.githubusercontent.com/6060545/161523156-02841ef7-3782-4d2c-b543-b514640f8cef.png)
![image](https://user-images.githubusercontent.com/6060545/161523224-43a75899-ab85-4f22-a599-c7c3695e2ad2.png)

**Comment by SimonCropp** [comment]
@anpin thanks so much for the help. i have raised an upstream issue here https://github.com/dotnet/runtime/issues/67529

on potential workaround would be to catch PlatformNotSupportedException and assume SupportsAutomaticDecompression is false.  @mattjohnsonpint thoughts?

**Comment by anpin** [comment]
@SimonCropp missed you reply and opened another issue in MAUI repo

**Comment by mattjohnsonpint** [comment]
@SimonCropp - the workaround sounds fine to me.  I made a PR with that.
