### ISSUE TITLE
flaky Environment_NotOnOptions_ValueFromEnvVar

### ISSUE THREAD

**Issue by SimonCropp** [getsentry/sentry-dotnet#1612]
```
NSubstitute.Exceptions.ReceivedCallsException: Expected to receive exactly 1 call matching:

NSubstitute.Exceptions.ReceivedCallsException
Expected to receive exactly 1 call matching:
	EnqueueEnvelope(e => (e.Items.Select(i => i.Payload).OfType().Select(i => i.Source).OfType().Single().Environment == "environment"))
Actually received 3 matching calls:
	EnqueueEnvelope(Envelope)
	EnqueueEnvelope(Envelope)
	EnqueueEnvelope(Envelope)

   at NSubstitute.Core.ReceivedCallsExceptionThrower.Throw(ICallSpecification callSpecification, IEnumerable`1 matchingCalls, IEnumerable`1 nonMatchingCalls, Quantity requiredQuantity)
   at NSubstitute.Routing.Handlers.CheckReceivedCallsHandler.Handle(ICall call)
   at NSubstitute.Routing.Route.Handle(ICall call)
   at NSubstitute.Core.CallRouter.Route(ICall call)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleForwardingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at NSubstitute.Proxies.CastleDynamicProxy.ProxyIdInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy_30.EnqueueEnvelope(Envelope envelope)
   at Else.AspNetCore.Tests.IntegrationMockedBackgroundWorker.<Environment_NotOnOptions_ValueFromEnvVar>b__19_0() in D:\Code\sentry-dotnet\test\Sentry.AspNetCore.Tests\IntegrationMockedBackgroundWorker.cs:line 305
   at Sentry.Testing.EnvironmentVariableGuard.WithVariableAsync(String key, String value, Func`1 asyncAction) in D:\Code\sentry-dotnet\test\Sentry.Testing\EnvironmentVariableGuard.cs:line 29
   at Else.AspNetCore.Tests.IntegrationMockedBackgroundWorker.Environment_NotOnOptions_ValueFromEnvVar() in D:\Code\sentry-dotnet\test\Sentry.AspNetCore.Tests\IntegrationMockedBackgroundWorker.cs:line 298
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

```

**Comment by mattjohnsonpint** [comment]
Haven't seen this except for this report.  Closing for now.  Lets reopen if it reoccurs.
