### ISSUE TITLE
Sentry JsonConverter can't handle IntPtr/UIntPtr/nint/nuint types.

### ISSUE THREAD

**Issue by Tyler-IN** [getsentry/sentry-dotnet#1735]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

6.0.6

### OS

Windows

### SDK Version

3.18.0

### Steps to Reproduce

Try to declare a context with a member of type nint, nuint, IntPtr, UIntPtr

### Expected Result

Member would be treated as an int, uint, long or ulong as appropriate for the platform.

### Actual Result

```
System.NotSupportedException: Serialization and deserialization of 'System.UIntPtr' instances are not supported.
   at System.Text.Json.Serialization.Converters.UnsupportedTypeConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
```

<details><summary>Expanded stack trace...</summary>

```
   at System.Text.Json.Serialization.Converters.UnsupportedTypeConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
   at Sentry.Internal.Extensions.JsonExtensions.WriteDynamicValue(Utf8JsonWriter writer, Object value, IDiagnosticLogger logger) in /_/src/Sentry/Internal/Extensions/JsonExtensions.cs:line 337
   at Sentry.Internal.Extensions.JsonExtensions.WriteDynamic(Utf8JsonWriter writer, String propertyName, Object value, IDiagnosticLogger logger) in /_/src/Sentry/Internal/Extensions/JsonExtensions.cs:line 351
   at Sentry.Internal.Extensions.JsonExtensions.WriteDictionaryValue(Utf8JsonWriter writer, IEnumerable`1 dic, IDiagnosticLogger logger) in /_/src/Sentry/Internal/Extensions/JsonExtensions.cs:line 151
   at Sentry.Contexts.WriteTo(Utf8JsonWriter writer, IDiagnosticLogger logger) in /_/src/Sentry/Protocol/Contexts.cs:line 95
   at Sentry.Internal.Extensions.JsonExtensions.WriteSerializableValue(Utf8JsonWriter writer, IJsonSerializable value, IDiagnosticLogger logger) in /_/src/Sentry/Internal/Extensions/JsonExtensions.cs:line 269
   at Sentry.Internal.Extensions.JsonExtensions.WriteSerializable(Utf8JsonWriter writer, String propertyName, IJsonSerializable value, IDiagnosticLogger logger) in /_/src/Sentry/Internal/Extensions/JsonExtensions.cs:line 279
   at Sentry.Internal.Extensions.JsonExtensions.WriteSerializableIfNotNull(Utf8JsonWriter writer, String propertyName, IJsonSerializable value, IDiagnosticLogger logger) in /_/src/Sentry/Internal/Extensions/JsonExtensions.cs:line 515
   at Sentry.SentryEvent.WriteTo(Utf8JsonWriter writer, IDiagnosticLogger logger) in /_/src/Sentry/SentryEvent.cs:line 242
   at Sentry.Protocol.Envelopes.JsonSerializable.SerializeAsync(Stream stream, IDiagnosticLogger logger, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/JsonSerializable.cs:line 35
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.Protocol.Envelopes.JsonSerializable.SerializeAsync(Stream stream, IDiagnosticLogger logger, CancellationToken cancellationToken)
   at Sentry.Protocol.Envelopes.EnvelopeItem.BufferPayloadAsync(IDiagnosticLogger logger, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/EnvelopeItem.cs:line 88
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.Protocol.Envelopes.EnvelopeItem.BufferPayloadAsync(IDiagnosticLogger logger, CancellationToken cancellationToken)
   at Sentry.Protocol.Envelopes.EnvelopeItem.SerializeAsync(Stream stream, IDiagnosticLogger logger, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/EnvelopeItem.cs:line 156
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.Protocol.Envelopes.EnvelopeItem.SerializeAsync(Stream stream, IDiagnosticLogger logger, CancellationToken cancellationToken)
   at Sentry.Protocol.Envelopes.Envelope.SerializeAsync(Stream stream, IDiagnosticLogger logger, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/Envelope.cs:line 82
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.Protocol.Envelopes.Envelope.SerializeAsync(Stream stream, IDiagnosticLogger logger, CancellationToken cancellationToken)
   at Sentry.Internal.Http.EnvelopeHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context) in /_/src/Sentry/Internal/Http/EnvelopeHttpContent.cs:line 30
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.Internal.Http.EnvelopeHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.InternalCopyToAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream)
   at Sentry.Internal.Http.GzipBufferedRequestBodyHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/GzipBufferedRequestBodyHandler.cs:line 63
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.Internal.Http.GzipBufferedRequestBodyHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Sentry.Internal.Http.RetryAfterHandler.<>n__0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Sentry.Internal.Http.RetryAfterHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/RetryAfterHandler.cs:line 65
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.Internal.Http.RetryAfterHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<>n__0(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Sentry.Internal.Http.HttpTransport.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/HttpTransport.cs:line 46
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.Internal.Http.HttpTransport.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken)
   at Sentry.Internal.BackgroundWorker.WorkerAsync() in /_/src/Sentry/Internal/BackgroundWorker.cs:line 123
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.Task.CancellationPromise`1.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.CompletionActionInvoker.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```
</details>

![exception](https://user-images.githubusercontent.com/33945568/174717725-4ad53f2b-4aaf-43f8-a450-165f56c93a28.png)
![call stack](https://user-images.githubusercontent.com/33945568/174717768-4a43a264-ca21-4b94-82f2-649a0cbfb05c.png)

**Comment by Tyler-IN** [comment]
Just add some JsonConverter impls or expand SentryJsonConverter to handle them.

**Comment by mattjohnsonpint** [comment]
Thanks for reporting this.  I was able to repro with:

```csharp
SentrySdk.CaptureMessage("Test", scope =>
{
    scope.Contexts["foo"] = new
    {
        Value = (IntPtr) 3
    };
});
```

It appears the .NET team decided that `IntPtr` and related types should not be serialized by STJ due to pitfalls with serializing/deserializing values between machines with different sized pointers. At one point they were serialized as empty values, but now they throw an exception.  See https://github.com/dotnet/runtime/issues/47685 and related PR.

However, since in Sentry we would just send such values as strings for informational purposes, it might make sense to add a converter to allow them for one-way serialization.

I also like the idea of exposing a mechanism to add additional converters.  Perhaps from `SentryOptions`.  We will discuss.
