### ISSUE TITLE
Many tests fail or don't run in Visual Studio + Net Framework only

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#1783]
All of the API Approval tests are failing when run in the default test runner on Visual Studio 2022 for Windows (same for both 17.2.6 current, and for 17.3.0 Preview 3.0), and only for .NET Framework targets.

On the same machine, the same tests pass fine either with `dotnet test` or in JetBrains Rider.

```
 Sentry.Tests.ApiApprovalTests.Run
   Source: ApiApprovalTests.cs line 7
   Duration: 372 ms

  Message: 
Mono.Cecil.AssemblyResolutionException : Failed to resolve assembly: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

  Stack Trace: 
BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
MetadataResolver.Resolve(TypeReference type)
TypeReference.Resolve()
AttributeFilter.ShouldIncludeAttribute(CustomAttribute attribute)
WhereEnumerableIterator`1.MoveNext()
Buffer`1.ctor(IEnumerable`1 source)
<GetEnumerator>d__1.MoveNext()
ApiGenerator.PopulateCustomAttributes(ICustomAttributeProvider type, CodeAttributeDeclarationCollection attributes, Func`2 codeTypeModifier, AttributeFilter attributeFilter)
ApiGenerator.PopulateCustomAttributes(ICustomAttributeProvider type, CodeAttributeDeclarationCollection attributes, AttributeFilter attributeFilter)
ApiGenerator.CreatePublicApiForAssembly(AssemblyDefinition assembly, Func`2 shouldIncludeType, Boolean shouldIncludeAssemblyAttributes, String[] whitelistedNamespacePrefixes, AttributeFilter attributeFilter)
ApiGenerator.GeneratePublicApi(Assembly assembly, ApiGeneratorOptions options)
ApiExtensions.CheckApproval(Assembly assembly, String filePath) line 12
ApiApprovalTests.Run() line 9
```

I created a separate test project that uses `PublicApiGenerator` to try to reproduce, and it passes fine.  So the problem is somewhere in the Sentry code base.

**Comment by mattjohnsonpint** [comment]
@SimonCropp - take a look please?

**Comment by mattjohnsonpint** [comment]
A whole bunch of other NetFX tests are failing in VS2022 also.  Too many to log.  Pretty much all of ASP.NET Core tests, and EF6 tests, and others.  Something is off...

**Comment by mattjohnsonpint** [comment]
Woah... Now I see that some tests aren't even running, and I get this on the "Show output from: Tests" in the output window:

```
========== Starting test run ==========
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (32-bit Desktop .NET 4.0.30319.42000)
[xUnit.net 00:00:00.22] Sentry.Tests: Catastrophic error during deserialization: System.ArgumentException: Could not load type 'Xunit.Sdk.SkippableFactTestCase, Xunit.SkippableFact' from serialization value 'Xunit.Sdk.SkippableFactTestCase, Xunit.SkippableFact:VGVzdE1ldGhvZDpYdW5pdC5TZGsuVGVzdE1ldGhvZCwgeHVuaXQuZXhlY3V0aW9uLntQbGF0Zm9ybX06VFdWMGFHOWtUbUZ0WlRwVGVYTjBaVzB1VTNSeWFXNW5PbFpYTlc5WlZ6VnJZa2RXYTFKWWFHcGFXRUl3WVZjNWRWZ3dXbkJqYlZaclZESTFSbVZIVG14alNGSndZakkxVm1KdGFHaGliVkp6V2xkU1NtSnNVbTlqYlZab1drRTlQUXBVWlhOMFEyeGhjM002V0hWdWFYUXVVMlJyTGxSbGMzUkRiR0Z6Y3l3Z2VIVnVhWFF1WlhobFkzVjBhVzl1TG50UWJHRjBabTl5YlgwNlZrZFdlbVJGVG5aaVIzaHNXVE5TY0dJeU5EWlhTRloxWVZoUmRWVXlVbkpNYkZKc1l6TlNSR0l5ZUhOYVYwNHdZVmM1ZFV4RFFqUmtWelZ3WkVNMWJHVkhWbXBrV0ZKd1lqSTBkV1V4UW5OWldGSnRZak5LZEdaVWNGTlNNbmcyV1RCa05HRkhWbFpPVjJocFZqRlZNbFpVVG5ObGJWSklWbTVTVFdKRk5IZFpNakZ6WkZad05tTkdaRk5OVm04eVYydFdUMUV5Um5SVFdHeHNVMFUxYUZacVFUQmtNV3hYV1hwV2ExWlhlRWxXTWpWaFlXMUdWbE5zVmxoaVIwMTRWRlZrVDJSWFJYcFdiR1JUVFZadk1sZHJWbTlVYlZKWFZHeG9UMVpGU21oV2FrcFRUbFprVjJGR1RtcFNNR3cxVkd4b2QxUlhSWGRYYWs1YVRVWmFWRnBITVV0WFJrcDFVVzFzYUUxR2NIbFdNVnB2VVRBeFIyTkdiRlJpUmxwb1ZqQlZNR1F4YTNwWmVteFJWVmhDVmxkc2FFOU5Sa1paVkc1d1lWWjZSbkJaYTJoeVRteGtTVlp1Vm1oWFJrWXhWbFJLVTJOcmVITlZiWGhxVFRGS1ExbDZUazlpUjBwWVUyNU9iRlV6Wkc1YVZXaFhaRmRHV1ZWWVZtRlhSMmh6VjFST1YwMUhSbGhQV0ZaTlltNVNVbGxyWkVkTlJuQjBUMWhzYVZkRVFUSldWbHB2VkRKV2MyTkdhRTVXTW5od1ZUQmtORlZzWkZkaFJrNXBUVVJzZWxaSGNGZGhhekI0VTI1T1dtSkZNSGhXYTJSVFUxWk9kVkZ0YkdsV01EQjVWbXhhYjJReVVYaGhNMmhZWWtkNFZsbHNhRzlqVm14MFkzcEdhR0pIZUhwWGExWnJWR3hKZUZOcmJGcE5SMUpRVmxkemVHTlhTa2xUYkdocFVtMDRkMWRzWkRSa01XUkdUbFpXVW1KWVFuQlpiR2hTWkRGWmVXUkhjRTlXVkVaSlZUSTFVMVl5Um5KVGJIQldUVVp3VEZsNlJuTk9iRkp6Vkd4d1RsWnNXVEZXYlRBeFZqSkZlRlJyV21sbGExcFdWV3BPYjFaR2JISmFSVFZzWWtaYU1Wa3dXbk5WTURGSlVXcE9XRlo2UlRCVWExcExWakpPUjJGR1VtaGhNWEJ2VmtaYWIySXdNVmRhU0U1b1VtdHdUMVZzVWxaTmJGVjVUVlU1VjJGNlJucFdNbkJIV1ZaS1dHRkZlRlZpUmxrd1dYcEdWMlJIVmtoalJUVk9WbGM0ZVZaclZtdE5SbFY0Vld4a1ZtRXdjRkpXYTFKRFZFWldWVk5VVm10V2JrSXdXV3RqTVZVeVNsaGxTSEJZWWtaVmVGbFZaRXRYUmxwVlYyeGFUazF1WnpKWGExWnJWakpTUm1WSVRsVmhhMHB4V1d4a05FMVdaSFZqU0dSV1lsWmFNVlZYTVhkV01rcElZVVpDV21FeVVsQmFSbHBUWkVaU2RHSkdaRTVTYlhkNlZqSjBWMkV5VVhoaE0yaFRWMGQ0VVZacVRsTmhSbHAwVGxjNVQySkhVbnBYV0hCSFZHeEpkMDVVUmxwV1JUVlVWMVphUzA1dFJYcGFSbkJwVmtWYVdWWkdWbUZpTVU1WFZtNVNiRkl6UWs5VVZsWjNZMVphYzFWcmRGZE5iRXBaVmxkMGMxWkhSbk5YYXpWYVlURndURmw2Um5OT2JGSnpWRzE0YVZJeWFFcFdWRWt4VVRKR1dGTnJiR2hTVm5CWldXdGtVMVJHVWxkWGJscHNVakZhU2xadE1VZFhSa3B5Vm1wT1YxSjZWak5WZWtaeVpVWmFXV0pHWkdsaVJuQjVWbFJDVjJSck1WZFZhMmhzVW1zMWNGVnFRWGhPYkZwWVRsaGtWVll3Y0ZoVk1qVjNWMjFGZDAxSWFGcFdla1pMV2xaVk1WZEZNVmhoUm1ST1lYcEJNVlZVU2pSWlYwcElWRzVXVldKclNuQlVWM0JTVFd4YVZWUnVUbXhpVmtwSlZtMDFVMVJYU2taT1NHUmFUV3BHZWxwR1duZE9iVTVHVGxkNFYxSnJhM2RXYTFKSFZHc3hTRlZZWkd4VFJWcFRWbXRTUWs5VlRuTldibFpvVjBWWmVGZHNWbk5TVlRselZHcFdhazB4U25OWmJFMHhWa2RTU1ZOdVFtbGlWMDB5VmpGamVGUnJNSGROV0VaaFpXdHdUMWxYZEZkTlJsSlZVMnRhVGsxRWJFVlVWVkpEV1ZaWmVGZHRPVlZTYkVwNVdsZHpOVlpXU2xsVmJVWlhVbGR6ZUZZeU1IaFpWMFpHVGtoc1ZtSlVSbEJXYWtKelRtdE9jbFZ0ZUZwTmJtaHZXVEl4UjAxSFJsaFBXRlpTVjBVMU5sZHNZM2hoVjBwSllrVTVXbFo2Um5OVU1uaFBUbGROZWxWdGVHbFZlbFpSVjFjeGQySkdhM3BWVlhSVFVqRmFjVmxyWkVkbFZteFpWVzVDYVUxcVZsWmFWbWhEWWtaU2RGSnVVbUZXU0VKVldsWm9UMDFHY0ZoTlNGWlZUV3R3ZUZkc1pFOU5RWEJFWWtkR2VtTXdSbnBqTWxaMFdXMTROVlJ0Um5SYVZIQlVaVmhPTUZwWE1IVlZNMUo1WVZjMWJrOXNWWGxXYmxaclUwVnZNVlJIZUZOaVIwMTZWVzV3VFZFd1NsaFhiR2hMWlcxR1dFOVlWbEZXUlRFeFZGWlNjbVJWTVVST1NHUk5VVEJLUlZwR1pEUk5SMUpaVTIxNFVWWjZWbk5hUm1oVFpWWnNXR1F6VGtwU2EwbDRWMWN4TkdOR2EzZGtSM2hzVm14S01sbFVTbGRrVmtKWVYyMXNXbFpGY0hOWFdIQlNUVlV4TmxwNlVtRldSWEJ2VjIxd1FsQlJjRVJpUjBaNll6RlNOV05IVms5WlZ6RnNUMnhPTldNelVteGlVelZVWkVoS2NHSnRZelpXVkVwWFpGZFNTVk5xVmsxaVJrcHpXWHBPVTJWcmVISmlTRlpyVWpGYWRWa3lNVWROUjBaWVQxaFdhbVZVVmtOWk1HaERVbGRKZVUxWGFHaFdlbFpEVjJ0a1IyUXlVa2hXYm14WFVqRmFObHBGYUU1UVVUMDkKVGVzdE1ldGhvZEFyZ3VtZW50czpTeXN0ZW0uT2JqZWN0CkRlZmF1bHRNZXRob2REaXNwbGF5OlN5c3RlbS5TdHJpbmc6UTJ4aGMzTkJibVJOWlhSb2IyUT0KRGVmYXVsdE1ldGhvZERpc3BsYXlPcHRpb25zOlN5c3RlbS5TdHJpbmc6VG05dVpRPT0KVGltZW91dDpTeXN0ZW0uSW50MzI6MApTa2lwcGluZ0V4Y2VwdGlvbk5hbWVzOlN5c3RlbS5TdHJpbmdbXTpSV3hsYldWdWRGUjVjR1U2VTNsemRHVnRMbE4wY21sdVp6cFZNMng2WkVkV2RFeHNUakJqYld4MVduYzlQUXBTWVc1ck9sTjVjM1JsYlM1SmJuUXpNam94Q2xSdmRHRnNUR1Z1WjNSb09sTjVjM1JsYlM1SmJuUXpNam94Q2t4bGJtZDBhREE2VTNsemRHVnRMa2x1ZERNeU9qRUtURzkzWlhKQ2IzVnVaREE2VTNsemRHVnRMa2x1ZERNeU9qQUtTWFJsYlRBNlUzbHpkR1Z0TGxOMGNtbHVaenBYU0ZaMVlWaFJkVlV5ZEhCalJWWTBXVEpXZDJSSGJIWmlaejA5'
Parameter name: serializedValue
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 35
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 84
   at Xunit.DefaultTestCaseBulkDeserializer.<BulkDeserialize>b__2_0(String serialization) in /_/src/xunit.runner.utility/Descriptor/DefaultTestCaseBulkDeserializer.cs:line 22
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Xunit.DefaultTestCaseBulkDeserializer.BulkDeserialize(List`1 serializations) in /_/src/xunit.runner.utility/Descriptor/DefaultTestCaseBulkDeserializer.cs:line 22
   at Xunit.Xunit2.BulkDeserialize(List`1 serializations) in /_/src/xunit.runner.utility/Frameworks/v2/Xunit2.cs:line 74
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in /_/src/xunit.runner.visualstudio/VsTestRunner.cs:line 565
[xUnit.net 00:00:00.22]   Starting:    Sentry.Tests
[xUnit.net 00:00:00.24]   Finished:    Sentry.Tests
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in 272.7 ms ==========
```


I give up.  VS test runner is borked.

**Comment by mattjohnsonpint** [comment]
Note - That shows xunit vs 2.4.5, but I got the same results with 2.4.3.  I temporarily tried a `net472` target to get 2.4.5 to work, just in case it was related to that.  But nope.

**Comment by mattjohnsonpint** [comment]
It appears that if I kick off the vstest runner from the *console* instead of visual studio, then all tests pass *except* the ApiApprovalTests that I logged above.  In other words, launch "Developer Command Prompt for VS2022", change to the sentry-dotnet solution root and do:

```
dotnet build test\Sentry.Tests
vstest.console test\Sentry.Tests\bin\Debug\net461\Sentry.Tests.dll
```

And you get lots of passed tests but just the one failure with the ApiApprovalTest.

So at least there is some difference between being in full Visual Studio or just using the vstest runner
