### ISSUE TITLE
Flaky test: BackgroundWorkerTests.FlushAsync_FullQueue_RespectsTimeout 

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#1864]
```
[xUnit.net 00:00:20.89]     Sentry.Tests.Internals.BackgroundWorkerTests.FlushAsync_FullQueue_RespectsTimeout [FAIL]

Error: Expected sw.Elapsed to be greater than 490ms, but found 487ms and 256.1µs.

  Failed Sentry.Tests.Internals.BackgroundWorkerTests.FlushAsync_FullQueue_RespectsTimeout [583 ms]
  Error Message:
   Expected sw.Elapsed to be greater than 490ms, but found 487ms and 256.1µs.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Primitives.SimpleTimeSpanAssertions`1.BeGreaterThan(TimeSpan expected, String because, Object[] becauseArgs)
   at Sentry.Tests.Internals.BackgroundWorkerTests.FlushAsync_FullQueue_RespectsTimeout() in D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\Internals\BackgroundWorkerTests.cs:line 389
--- End of stack trace from previous location ---
  Standard Output Messages:
 [Debug 00:00:00.00]: Starting BackgroundWorker.
 [Debug 00:00:00.00]: Enqueuing envelope 8a4a9aa47cd[64](https://github.com/getsentry/sentry-dotnet/runs/7910945253?check_suite_focus=true#step:6:65)613a6aa6f48cf98e929
 [Debug 00:00:00.00]: BackgroundWorker Started.
 [Debug 00:00:00.00]: Tracking depth: 1.
 [Debug 00:00:00.48]: Timeout when trying to flush queue.
 [Debug 00:00:00.58]: Disposing BackgroundWorker.
 [Debug 00:00:00.58]: Exiting immediately due to 0 shutdown timeout. #1 in queue.
 [Warning 00:00:00.58]: Worker stopped while 1 were still in the queue.
```

https://github.com/getsentry/sentry-dotnet/runs/7910945253?check_suite_focus=true#step:6:65

**Comment by mattjohnsonpint** [comment]
The problem is when we call `CancellationTokenSource.CancelAfter(TimeSpan)`, that's using a `System.Threading.Timer` under the hood - which doesn't have great precision.
