### ISSUE TITLE
MAUI, iOS simulator. "ResolveNativeReferences" exception.

### ISSUE THREAD

**Issue by Nick4nik** [getsentry/sentry-dotnet#2037]
### Package

Sentry.Maui

### .NET Version

6.0.0 (or 7.0.0)

### OS

iOS

### SDK Version

3.23.1-preview.3

### Steps to Reproduce

1. Create a new MAUI project.
2. Open .csproj-file.
3. Add a reference
````
<PackageReference Include="Sentry.Maui" Version="3.23.1-preview.3" />
````
4. Rebuild this project and try to run it on the iOS simulator.

### Expected Result

Project should be successfully started.

### Actual Result

This exception is thrown at compile time. It's 100% about Sentry, cause with other packages I don't get any errors.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ResolveNativeReferences" task failed unexpectedly.
System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Xamarin.Utils.Execution.<>c__DisplayClass24_1.<RunAsync>b__0() in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Execution.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Xamarin.MacDev.Tasks.XamarinTask.<ExecuteAsync>d__24.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs:line 120
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Xamarin.MacDev.Tasks.ResolveNativeReferencesBase.ProcessSidecar(ITaskItem r, String resources, List`1 native_frameworks) in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs:line 134
   at Xamarin.MacDev.Tasks.ResolveNativeReferencesBase.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs:line 105
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Xamarin.Utils.Execution.<>c__DisplayClass24_1.<RunAsync>b__0() in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Execution.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Xamarin.MacDev.Tasks.XamarinTask.<ExecuteAsync>d__24.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs:line 120<---
	MauiApp2	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.0.527\tools\msbuild\iOS\Xamarin.Shared.targets	137	

```
![image](https://user-images.githubusercontent.com/104008097/200889803-96749efd-44cd-47e5-99a6-b2350efedcfa.png)

**Comment by mattjohnsonpint** [comment]
Thanks for reporting.  Can you also please tell me a bit about your dev environment?

- Windows or Mac?
  - If Windows, are you using "Pair to Mac"?
- IDE (VS or Rider) and version
- Output of `dotnet --info` run from your solution dir
- Are you targeting .NET 6 or .NET 7 in your MAUI app?

**Comment by mattjohnsonpint** [comment]
Also, try updating your workloads as well with  `dotnet workload update`  (or `sudo dotnet workload update` on mac) - run from your solution dir to pick up the correct version if you've got any `global.json` files. If installed via Visual Studio, also check VS Installer for updates.  Thanks.

**Comment by mattjohnsonpint** [comment]
Thanks for the details.  I will research and get back to you.

FYI, We've fully tested directly on a Mac, and on real iOS devices.  From Windows, we've encountered some issues with Hot Restart (see #1961), which we'll have a workaround for soon.  There may be some similar workaround needed for Pair to Mac.

Also. is your Mac updated with XCode 14 or still using XCode 13?

**Comment by Nick4nik** [comment]
Oh, I forgot that. XCode 13.4.1.
Thanks for that.

**Comment by mattjohnsonpint** [comment]
FYI, I was able to reproduce the problem.  I will add more details when I have investigated further.  Thanks.

**Comment by mattjohnsonpint** [comment]
This appears to be a bug in Xamarin.iOS.  See https://github.com/xamarin/xamarin-macios/issues/16001#issuecomment-1252984909 which is a near exact duplicate.

**Comment by mattjohnsonpint** [comment]
Not sure that we're going to be able to workaround this one.  Until Microsoft has a fix, I suggest one of the following:

- Develop on a Mac, which appear to always work
- Develop on Windows but deploy to a real device instead of the simulator.  (You'll need the Hot Restart workaround, or to wait until the next Sentry release which will have it built in.  See: #1961)
- Disable Sentry while developing on Windows
  - This may be difficult though, as you'd have to both conditionally exclude the package reference and any code using it.

If a workaround becomes apparent, we'll add it.  Thanks.

**Comment by bozau** [comment]
This is quite a disapointing flaw within MAUI, I actually just purchased a MacOS mini within the past week or two to be able to emulate a completely new MAUI project (no additional libs etc) only to run up against this issue.

It's getting to the point where I question if developing with MAUI is even reasonably feasible?

**Comment by mattjohnsonpint** [comment]
@bozau - Yes - Microsoft is working on this with xamarin/xamarin-macios#16001.

Also, I just developed a workaround we can use for Sentry.  It's not a general-purpose workaround for the whole issue, but it side-steps us running into it by preventing the resources zip file from being created to begin with.  It will be released shortly.  Thanks.
