### ISSUE TITLE
Flaky test: FlushOnDispose_SendsEnvelope

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2156]
Flaky test on Android.  We see this often.

https://github.com/getsentry/sentry-dotnet/actions/runs/4087239760/attempts/1#summary-11098373861

Sentry.Tests.HubTests.FlushOnDispose_SendsEnvelope(cachingEnabled: True) - Failed

```
NSubstitute.Exceptions.ReceivedCallsException : Expected to receive exactly 1 call matching:
	SendEnvelopeAsync(any Envelope, any CancellationToken)
Actually received no matching calls.
at NSubstitute.Core.ReceivedCallsExceptionThrower.Throw(ICallSpecification callSpecification, IEnumerable`1 matchingCalls, IEnumerable`1 nonMatchingCalls, Quantity requiredQuantity)
   at NSubstitute.Routing.Handlers.CheckReceivedCallsHandler.Handle(ICall call)
   at NSubstitute.Routing.Route.Handle(ICall call)
   at NSubstitute.Core.CallRouter.Route(ICall call)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleForwardingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at NSubstitute.Proxies.CastleDynamicProxy.ProxyIdInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy_4.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken)
   at Sentry.Tests.HubTests.FlushOnDispose_SendsEnvelope(Boolean cachingEnabled)
--- End of stack trace from previous location ---
```

**Comment by mattjohnsonpint** [comment]
I can't repro this locally.  Will just skip in CI for now.

**Comment by jamescrosswell** [comment]
This seems to be back again:
- https://github.com/getsentry/sentry-dotnet/actions/runs/14894792967/job/41835076586?pr=4164
