### ISSUE TITLE
Async RequestPayloadExtractor?

### ISSUE THREAD

**Issue by k-arl** [getsentry/sentry-dotnet#219]
The DefaultRequestPayloadExtractor has a comment stating that there would be no real value in making it asynchronous.
https://github.com/getsentry/sentry-dotnet/blob/e24115df3869601fb51a3d37392ae031a9ddb83b/src/Sentry/Extensibility/DefaultRequestPayloadExtractor.cs#L21

Whilst there might not be any gain in performance by making it async, I would like to suggest a scenario where there would be value in doing so.

There is nowhere in our APIs where we need to use synchronous IO, so to prevent developers from doing so accidentally, we configure Kestrel to disallow it:

```c#
builder.UseKestrel(options =>
{
    options.AllowSynchronousIO = false;
});
```

However setting those Kestrel options combined with Sentry reading the body synchronously means that when logging an exception to Sentry, we get an additional exception in the breadcrumbs in the event and the request body is also not part of the event because it could not be read.

```
Failed invoking event handler: System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at Sentry.Extensibility.DefaultRequestPayloadExtractor.DoExtractPayLoad(IHttpRequest request) in C:\projects\sentry-dotnet\src\Sentry\Extensibility\DefaultRequestPayloadExtractor.cs:line 22
   at Sentry.Extensibility.BaseRequestPayloadExtractor.ExtractPayload(IHttpRequest request) in C:\projects\sentry-dotnet\src\Sentry\Extensibility\BaseRequestPayloadExtractor.cs:line 19
   at Sentry.Extensibility.RequestBodyExtractionDispatcher.ExtractPayload(IHttpRequest request) in C:\projects\sentry-dotnet\src\Sentry\Extensibility\RequestBodyExtractionDispatcher.cs:line 41
   at Sentry.AspNetCore.ScopeExtensions.SetBody(BaseScope scope, HttpContext context, SentryAspNetCoreOptions options) in C:\projects\sentry-dotnet\src\Sentry.AspNetCore\ScopeExtensions.cs:line 109
   at Sentry.AspNetCore.ScopeExtensions.Populate(Scope scope, HttpContext context, SentryAspNetCoreOptions options) in C:\projects\sentry-dotnet\src\Sentry.AspNetCore\ScopeExtensions.cs:line 43
   at Sentry.AspNetCore.SentryMiddleware.PopulateScope(HttpContext context, Scope scope) in C:\projects\sentry-dotnet\src\Sentry.AspNetCore\SentryMiddleware.cs:line 143
   at Sentry.Scope.Evaluate() in C:\projects\sentry-dotnet\src\Sentry\Scope.cs:line 135
```

**Comment by bruno-garcia** [comment]
Please correct if I'm wrong but this would only happen if an exception happened in the pipeline before your request body was read by, for example, model binding. Is that right?
The reason it's synchronous is, mainly, because the body will be buffered already. Hence it's just moving data around in memory.

Nonetheless it's a valid reason to make it asynchronous it's just more complexity and work to get it done.

**Comment by k-arl** [comment]
You're completely right, my mistake.

I originally had a quick test method set up where no model binding or anything was taking place so the body was not being read before the exception occurred. Once I updated my test method, Sentry worked as I would expect it to.

I guess the original point still stands but is fairly low priority.

Thanks for your help!

**Comment by m4rcelpl** [comment]
In .NET Core 3 (preview 6) options.AllowSynchronousIO i set to false by default and sentry generate this error ;/
Manual set this to true solving a problem. Please set higher priority :)

**Comment by bruno-garcia** [comment]
I guess it's time to start a branch `3.0.0-preview` depending on the aspnet core `3.0.0-preview 6` bits and multi-targeting netcoreapp3.0. Any takers? :)

**Comment by bruno-garcia** [comment]
Ended up raising another one. This is marked as a bug now.

ASP.NET Core 3 is throwing an exception when attempting to reading from the request body synchronously **even if buffering was enabled and the request was already read asynchronously prior**.

This means we need to change the request reading interface (`IRequestPayloadExtractor`) to be async.

The fix is:

Change from:
```
        object ExtractPayload(IHttpRequest request);
```
To:
```
        ValueTask<object> ExtractPayloadAsync(IHttpRequest request, CancellationToken token);
```

This must fit the 2.0.0 release since it breaks users on ASP.NET Core 3

**Comment by Seeker1437** [comment]
I am going to take a look and see if I can help with this because I kinda need this to be async.

**Comment by bruno-garcia** [comment]
@Seeker1437 Highly appreciated. 
I believe it means changing the signature to return `Task` instead of `void` and method name to have suffix `Async` and take a `CancellationToken`. Then have this "bubble" all the way (change the signature of all the methods involved until you reach something in ASP.NET Core that is async (middleware if I recall correctly).

I suggest opening a draft PR quickly (no tests for example, even tests project not compiling it's OK). so we can review things and discuss.

It's OK for this to be a breaking change, I've been holding off 2.0.0 to fit breaking changes.

**Comment by lol768** [comment]
Please do fix this.

**Comment by bruno-garcia** [comment]
@lol768 It will be fixed soon.
