### ISSUE TITLE
Visual Basic ASP.NET App Not Reporting Errors

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2232]
### Discussed in https://github.com/getsentry/sentry-dotnet/discussions/2230

<div type='discussions-op-text'>

<sup>Originally posted by **tankerkiller125** March 13, 2023</sup>
We're working on adding Sentry to one of our legacy ASP.NET VB applications (using .NET 4.8) and so far it seems to be working OK (HTTP request timings are being sent), however when we attempt to send errors nothing comes over. We also looked through the Sentry debug and it seems that the error capture isn't firing at all.

Below is the code we have for our Global.asax.vb file:

```vb
Imports System
Imports System.Web
Imports Sentry
Imports Sentry.AspNet
Imports Sentry.Extensibility

Public Class MvcApplication
    Inherits HttpApplication

    Private _sentry As IDisposable

    Protected Sub Application_Start()
        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
        _sentry = SentrySdk.Init(Function(o)
                                     o.Dsn = "https://dsn@self-host-sentry.tld/1"
                                     o.TracesSampleRate = 1.0
                                     o.AddAspNet()
                                     o.SendDefaultPii = True
                                     o.Debug = True
                                 End Function)
    End Sub

    Protected Sub Application_Error()
        Server.CaptureLastError()
    End Sub

    Protected Sub Application_BeginRequest()
        Context.StartSentryTransaction()
    End Sub

    Protected Sub Application_EndRequest()
        Context.FinishSentryTransaction()
    End Sub

    Protected Sub Application_End()
        _sentry?.Dispose()
    End Sub
End Class
```

We also tried:
```vb
SentrySdk.CaptureException(Server.GetLastError)
```
and that didn't seem to work either.

Any assistance would be greatly appreciated.</div>

**Comment by mattjohnsonpint** [comment]
@tankerkiller125 - I just tried the latest Sentry SDK on a new .NET Framework 4.8 VB.NET ASP.NET Web Forms project, using the code you showed (similar to our docs).  It worked for me.  I threw an exception from one of the web pages, and it correctly captured and presented in Sentry (SaaS).

Can I ask for some more details please?  What version of the SDK? What version of Sentry self-hosted?  Is yours a WebForms or WebAPI or MVC project?  If you try in VS and set a breakpoint in `Application_Error`, does it reach that breakpoint?

Thanks.

**Comment by tankerkiller125** [comment]
What version of the SDK?
Latest version published

What version of Sentry self-hosted?
23.3.0.dev0 74e5545

Is yours a WebForms or WebAPI or MVC project? 
WebForms I believe (each page as an ASPX page)

How and where specifically are you throwing the error?
We are purposefully throwing an error on a file called "PageTask.aspx", notably we are passing an object to an SQL query (which should be using a string) causing an SQL error to be returned from the server (500 error)
 
If you try in VS and set a breakpoint in Application_Error, does it reach that breakpoint?
It does reach the breakpoint.

After digging deeper this morning we finally got an actual Stack trace error out of the sentry package:
```
Exception thrown: 'System.ArgumentException' in mscorlib.dll
  Error: An error occurred when capturing the event c8c81ebbe9c949baace4abc548627d03.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Sentry.AspNet.Internal.SystemWebRequestEventProcessor.Process(SentryEvent event)
   at Sentry.SentryClient.DoSendEvent(SentryEvent event, Scope scope)
   at Sentry.SentryClient.CaptureEvent(SentryEvent event, Scope scope)
  Debug: Ending transaction as Aborted, due to unhandled exception.
  Debug: Enqueuing envelope b0bb5fe714374552b769b71b9e96f470
  Debug: Envelope handed off to transport (event ID: 'b0bb5fe714374552b769b71b9e96f470'). 1 items in queue.
   Info: Envelope queued up: 'b0bb5fe714374552b769b71b9e96f470'
  Debug: Enqueuing envelope 9c027b5922334bbeb05bf09bd62768f4
   Info: Envelope queued up: '9c027b5922334bbeb05bf09bd62768f4'
```

We do not get this error with a different project we added sentry to (the same overall setup, .NET 4.8, WebForms, etc.) and error reporting is working on that project.

**Comment by mattjohnsonpint** [comment]
Thanks for the stack trace.  The only place I can find in our code where that would originate is here:

https://github.com/getsentry/sentry-dotnet/blob/3d79087ae909c4928ca2acd62cbfddce073726fc/src/Sentry.AspNet/Internal/SystemWebRequestEventProcessor.cs#L79

Either you've already added the `IsAuthenticated` key to `event.User.Other` somewhere else in your code, or this line is somehow being called twice.  On the latter, the only way I can see that happening naturally is if you've inadvertently called `AddAspNet` twice.

We should probably be resilient to both, but could you check your code to see if either is the case?

Thanks.

**Comment by tankerkiller125** [comment]
Digging in we did accidently call o.AddAspNet twice. Which caused the error.

Huge thanks for assistance!.

It would be nice if the library handled that though just in case someone else does the same thing. I'm actually a bit surprised that the IDE nor any of our other tooling didn't warn or error out on it.
