### ISSUE TITLE
Failing to report issues via Blazor WebAssembly

### ISSUE THREAD

**Issue by mdemler** [getsentry/sentry-dotnet#2499]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

7

### OS

Browser

### SDK Version

3.34.0

### Steps to Reproduce

1.  Run the Sentry.Samples.AspNetCore.Blazor.Wasm sample project.
2.  Attempt to trigger the issue report.
3. Check console window or debugger output window
4. Note failure

### Expected Result

This obviously used to work and should work.

### Actual Result

Report failed:

```
System.PlatformNotSupportedException: System.Diagnostics.Process is not supported on this platform.
   at System.Diagnostics.Process.GetCurrentProcess()
   at Sentry.Internal.ILSpy.SingleFileApp.FromMainModule()
   at System.Lazy`1[[Sentry.Internal.ILSpy.SingleFileApp, Sentry, Version=3.34.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[Sentry.Internal.ILSpy.SingleFileApp, Sentry, Version=3.34.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[Sentry.Internal.ILSpy.SingleFileApp, Sentry, Version=3.34.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0]].CreateValue()
   at System.Lazy`1[[Sentry.Internal.ILSpy.SingleFileApp, Sentry, Version=3.34.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0]].get_Value()
   at Sentry.Internal.ILSpy.SingleFileApp.get_MainModule()
   at Sentry.Internal.DebugStackTrace.GetDebugImage(Module module, SentryOptions options)
   at Sentry.Internal.DebugStackTrace.AddDebugImage(Module module)
   at Sentry.Internal.DebugStackTrace.InternalCreateFrame(StackFrame stackFrame, Boolean demangle)
   at Sentry.Internal.DebugStackTrace.CreateFrame(StackFrame stackFrame)
   at Sentry.Internal.DebugStackTrace.CreateFrames(StackTrace stackTrace, Boolean isCurrentStackTrace)+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[SentryStackFrame](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1[[Sentry.SentryStackFrame, Sentry, Version=3.34.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0]]..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ReverseIterator`1[[Sentry.SentryStackFrame, Sentry, Version=3.34.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0]].MoveNext()
   at Sentry.Internal.DebugStackTrace.Create(SentryOptions options, StackTrace stackTrace, Boolean isCurrentStackTrace)
   at Sentry.Extensibility.SentryStackTraceFactory.Create(Exception exception)
   at Sentry.Internal.MainExceptionProcessor.BuildSentryException(Exception exception, Int32 id, Nullable`1 parentId, String source)
   at Sentry.Internal.MainExceptionProcessor.WalkExceptions(Exception exception, Counter counter, Nullable`1 parentId, String source)+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[SentryException](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1[[Sentry.Protocol.SentryException, Sentry, Version=3.34.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0]]..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ReverseIterator`1[[Sentry.Protocol.SentryException, Sentry, Version=3.34.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0]].MoveNext()
   at System.Collections.Generic.List`1[[Sentry.Protocol.SentryException, Sentry, Version=3.34.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0]]..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[SentryException](IEnumerable`1 source)
   at Sentry.Internal.MainExceptionProcessor.CreateSentryExceptions(Exception exception)
   at Sentry.Internal.MainExceptionProcessor.Process(Exception exception, SentryEvent sentryEvent)
   at Sentry.SentryClient.DoSendEvent(SentryEvent event, Hint hint, Scope scope)
   at Sentry.SentryClient.CaptureEvent(SentryEvent event, Hint hint, Scope scope)
```

**Comment by jamescrosswell** [comment]
Thanks for reporting @mdemler - I can reproduce this so we'll look into it.
