### ISSUE TITLE
Finish_SentryRequestTransactionGetsIgnored test fails intermittently

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2588]
This test doesn't appear to be deterministic and [fails intermittently](https://github.com/getsentry/sentry-dotnet/actions/runs/6036452819/job/16378781321).

```
[xUnit.net 00:00:04.17]     Sentry.Tests.Protocol.TransactionTests.Finish_SentryRequestTransactionGetsIgnored [FAIL]

Error: Expected transaction.IsFinished to be false, but found True.

  Failed Sentry.Tests.Protocol.TransactionTests.Finish_SentryRequestTransactionGetsIgnored [39 ms]
  Error Message:
   Expected transaction.IsFinished to be false, but found True.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
   at Sentry.Tests.Protocol.TransactionTests.Finish_SentryRequestTransactionGetsIgnored() in /home/runner/work/sentry-dotnet/sentry-dotnet/test/Sentry.Tests/Protocol/TransactionTests.cs:line 474
--- End of stack trace from previous location ---
```

**Comment by bitsandfoxes** [comment]
Have not seen that one in a while.
