### ISSUE TITLE
Sentry has Unresolvable Dependencies in .NET Framework

### ISSUE THREAD

**Issue by ReinhardtJ** [getsentry/sentry-dotnet#2737]
### Package

Sentry

### .NET Flavor

.NET Framework

### .NET Version

4.8

### OS

Windows

### SDK Version

3.40.1

### Steps to Reproduce

I have a .NET Framework 4.8 project which executes the following code - essentially the sample code from the docs
```cs
SentrySdk.Init(o =>
            {
                // Tells which project in Sentry to send events to:
                o.Dsn = "<my-dns>";

                // When configuring for the first time, to see what the SDK is doing:
                o.Debug = true;

                // Set traces_sample_rate to 1.0 to capture 100% of transactions for performance monitoring.
                // We recommend adjusting this value in production.
                o.TracesSampleRate = 1.0;

                // Enable Global Mode since this is a client app
                o.IsGlobalModeEnabled = true;

                //TODO: any other options you need go here
            });
            SentrySdk.CaptureMessage("Hello from Plugin");
```

**Additional Notes**
I am using the Sentry in a WPF application. In the docs there is a note which says that I should init Sentry in the ctor of my Applicaion Class. Since I am developing an Add-On for a 3rd Party Application using Xarial Xcad (https://xcad.xarial.com/) I don't have direct access to the Applications ctor. I have to resort using the ctor of the Add-In class provided by the Xarial Xcad Framework. This is where I call the above code from.

### Expected Result

When I initialize Sentry as specified in the docs and call `SentrySdk.CaptureMessage("Hello from Plugin");` there should be no error and the message should appear in our Sentry dashboard.

### Actual Result

When I run this code, I get the following output: (I only left the presumably important part, but I can include everything if that is important)
```sh
(...)
 Debug: Enqueuing envelope 8f73d8a1fa174a1b8e47416b9587e470
   Info: Envelope queued up: '8f73d8a1fa174a1b8e47416b9587e470'
  Error: Failed to serialize Envelope into the network stream
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Threading.Tasks.ValueTask.get_IsCompleted()
   at System.Runtime.CompilerServices.ValueTaskAwaiter.get_IsCompleted()
   at Sentry.Protocol.Envelopes.Envelope.<SerializeHeaderAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Sentry.Protocol.Envelopes.Envelope.<SerializeAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Sentry.Internal.Http.EnvelopeHttpContent.<SerializeToStreamAsync>d__4.MoveNext()

=== Pre-bind state information ===
LOG: DisplayName = System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                                                                                                                             (Fully-specified)
LOG: Appbase = file:///C:/PROGRA~1/SOLIDW~1/SOLIDW~1/
LOG: Initial PrivatePath = NULL
Calling assembly : System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: The same bind was seen before, and was failed with hr = 0x80070002.

  Debug: Envelope handed off to transport (event ID: '8f73d8a1fa174a1b8e47416b9587e470'). 1 items in queue.
  Error: Error while processing envelope (event ID: '8f73d8a1fa174a1b8e47416b9587e470'). 1 items in queue.
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.Threading.Tasks.ValueTask.get_IsCompleted()
   at System.Runtime.CompilerServices.ValueTaskAwaiter.get_IsCompleted()
   at Sentry.Protocol.Envelopes.Envelope.<SerializeHeaderAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Sentry.Protocol.Envelopes.Envelope.<SerializeAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Sentry.Internal.Http.EnvelopeHttpContent.<SerializeToStreamAsync>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Sentry.Internal.Http.GzipBufferedRequestBodyHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Sentry.Internal.Http.RetryAfterHandler.<SendAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Sentry.Internal.Http.HttpTransport.<SendEnvelopeAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Sentry.Internal.BackgroundWorker.<DoWorkAsync>d__20.MoveNext()
  Debug: De-queueing event 8f73d8a1fa174a1b8e47416b9587e470
```

I read this output as Sentry expecting `System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1` to be installed. If I do install this version by incuding `<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.0.4.1" />` in my .csproj file, i get the following error on build

```sh
0>Optimate.AddIn.Core.csproj: Warning NU1603 : Optimate.AddIn.Core depends on System.Runtime.CompilerServices.Unsafe (>= 4.0.4.1) but System.Runtime.CompilerServices.Unsafe 4.0.4.1 was not found. An approximate best match of System.Runtime.CompilerServices.Unsafe 4.3.0 was resolved.
0>Optimate.AddIn.Core.csproj: Error NU1605 : Warning As Error: Detected package downgrade: System.Runtime.CompilerServices.Unsafe from 5.0.0 to 4.3.0. Reference the package directly from the project to select a different version. 
 Optimate.AddIn.Core -> Sentry 3.40.1 -> System.Text.Json 5.0.2 -> System.Runtime.CompilerServices.Unsafe (>= 5.0.0) 
 Optimate.AddIn.Core -> System.Runtime.CompilerServices.Unsafe (>= 4.0.4.1)
```

So when trying to build a Project with Sentry 3.40.1 it requires System.Runtime.CompilerServices.Unsafe version 5.0.0.

**Comment by bitsandfoxes** [comment]
Hey @ReinhardtJ, sorry to see you run into issues. Generally, the SDK does not offer support for use in libraries.
It looks to me like the dependencies of the 3rd Party Application and Sentry SDK are conflicting.
The SDK has a dependency on `System.Text.Json (>= 5.0.2)` which itself has a dependency on `System.Runtime.CompilerServices.Unsafe (>= 5.0.0)`.
I don't think getting Xarial Xcad to update another workaround I can offer is the [dotnet-assembly-alias](https://github.com/getsentry/dotnet-assembly-alias) tool. We're using this tool in the Unity SDK to resolve those dependencies. As a tldr; it "deeply" renames your projects dependencies to exactly resolve these kinds of conflicts.

**Comment by ReinhardtJ** [comment]
@bitsandfoxes Thank you for your time and answer. 

I investigated further and discorvered that redis has had the same problem with the "Unsafe" dll (https://github.com/StackExchange/StackExchange.Redis/issues/1128). To summarize it, it is a problem of Microsoft tooling, therefore neither caused by Sentry nor by my application nor its other dependencies. 

If someone experiences the same issue, there are workarounds. The one that worked in my case was https://stackoverflow.com/a/73914330/11119340

**Comment by bitsandfoxes** [comment]
Thanks for the update!
