### ISSUE TITLE
 Failed to extract body.

### ISSUE THREAD

**Issue by wondertalik** [getsentry/sentry-dotnet#2958]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET Core

### .NET Version

8.0.0

### OS

macOS

### SDK Version

8.0.0

### Steps to Reproduce

After migrate from net7 to net8, i geta an error `System.IO.IOException: The client reset the request stream.` every time when load a web page.

Have installed packages v.3.41.3:
- Sentry
- Sentry.AspNetCore
- Sentry.Serilog

### Expected Result

without exception

### Actual Result

```
[12:10:09 INF] Sentry trace header is null. Creating new Sentry Propagation Context.
[12:10:09 INF] Started transaction with span ID 'b6d12508ef62fdcf' and trace ID 'c8c8ff3ae7fa492ba09251f8de8f62a6'.
[12:10:09 INF] Started transaction with span ID 'b6d12508ef62fdcf' and trace ID 'c8c8ff3ae7fa492ba09251f8de8f62a6'.
[12:10:09 ERR] Failed to extract body.
System.IO.IOException: The client reset the request stream.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal(CancellationToken cancellationToken)
   at Sentry.Extensibility.DefaultRequestPayloadExtractor.DoExtractPayLoad(IHttpRequest request)
   at Sentry.Extensibility.BaseRequestPayloadExtractor.ExtractPayload(IHttpRequest request)
   at Sentry.Extensibility.RequestBodyExtractionDispatcher.ExtractPayload(IHttpRequest request)
   at Sentry.AspNetCore.ScopeExtensions.SetBody(Scope scope, HttpContext context, SentryAspNetCoreOptions options)
   at Sentry.AspNetCore.ScopeExtensions.Populate(Scope scope, HttpContext context, SentryAspNetCoreOptions options)
[12:10:09 INF] Envelope queued up: '91584c8c94564b0eae95c10d3838fa76'
[12:10:09 INF] Envelope queued up: 'fd8e25c87b084049b6559a6a04e38de1'
[12:10:09 INF] HTTP GET / responded 307 in 2182.2581 ms
[12:10:09 INF] Envelope queued up: 'ef73c2b37c7b4be88562bd168060a7bb'
[12:10:09 INF] Envelope queued up: 'c3de0e49d0024e49aef708b3fc197718'
[12:10:09 INF] HTTP GET /es/ responded 200 in 337.7770 ms
```

**Comment by bitsandfoxes** [comment]
Hey, sorry you're experiencing issues and thanks for reaching out.
Could you share a bit more about your setup or maybe even share a repro? It's hard to tell what's going on just based on those logs.

**Comment by bruno-garcia** [comment]
```
System.IO.IOException: The client reset the request stream.
```

Looks to me the client (browser for example) cancelled the request, so nothing to do in this case other than log internally and continue with capturing the event without a body.

**Comment by bitsandfoxes** [comment]
Closing this as stale. Please feel free to reopen this.
