### ISSUE TITLE
Flaky test: Error: Expected options.TransactionProfilerFactory to be <null>, but found Sentry.Profiling.SamplingTransactionProfilerFactory

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3009]
Fix flakey tests and turn it back on.

https://github.com/getsentry/sentry-dotnet/actions/runs/7424856180/job/20205336624?pr=3004

```
Error: Expected options.TransactionProfilerFactory to be <null>, but found Sentry.Profiling.SamplingTransactionProfilerFactory
{
}.

  Failed Sentry.Profiling.Tests.SamplingTransactionProfilerTests.Profiler_ThrowingOnSessionStartup_DoesntBreakSentryInit [762 ms]
  Error Message:
   Expected options.TransactionProfilerFactory to be <null>, but found Sentry.Profiling.SamplingTransactionProfilerFactory
{
}.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.BeNull(String because, Object[] becauseArgs)
   at Sentry.Profiling.Tests.SamplingTransactionProfilerTests.Profiler_ThrowingOnSessionStartup_DoesntBreakSentryInit() in /Users/runner/work/sentry-dotnet/sentry-dotnet/test/Sentry.Profiling.Tests/SamplingTransactionProfilerTests.cs:line 322
   at Sentry.Profiling.Tests.SamplingTransactionProfilerTests.Profiler_ThrowingOnSessionStartup_DoesntBreakSentryInit() in /Users/runner/work/sentry-dotnet/sentry-dotnet/test/Sentry.Profiling.Tests/SamplingTransactionProfilerTests.cs:line 341
--- End of stack trace from previous location ---
  Standard Output Messages:
 [Debug 00:00:00.01]: Initializing Hub for Dsn: 'https://d4d82fc1c2c4032a83f3a29aa3a3aff@fake-sentry.io:65535/2147483647'.
 [Debug 00:00:00.01]: This looks like a standard JIT/AOT application build.
 [Debug 00:00:00.01]: Starting BackgroundWorker.
 [Debug 00:00:00.01]: New scope pushed.
 [Debug 00:00:00.01]: Registering integration: 'AutoSessionTrackingIntegration'.
 [Debug 00:00:00.01]: Registering integration: 'AppDomainUnhandledExceptionIntegration'.
 [Debug 00:00:00.01]: Registering integration: 'AppDomainProcessExitIntegration'.
 [Debug 00:00:00.01]: Registering integration: 'UnobservedTaskExceptionIntegration'.
 [Debug 00:00:00.01]: Registering integration: 'SentryDiagnosticListenerIntegration'.
 [Debug 00:00:00.01]: Registering integration: 'WinUIUnhandledExceptionIntegration'.
 [Debug 00:00:00.01]: Registering integration: 'ProfilingIntegration'.
 [Debug 00:00:00.01]: BackgroundWorker Started.
 [Info 00:00:00.76]: Disposing the Hub.
 [Debug 00:00:00.76]: Successfully flushed all events up to call to FlushAsync.
```

**Comment by bruno-garcia** [comment]
Another run failed with it: https://github.com/getsentry/sentry-dotnet/actions/runs/7425866455/job/20208407060?pr=3004#step:14:1580

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry-dotnet/actions/runs/7392979628/job/20159099907?pr=2999#step:14:442
