### ISSUE TITLE
Flaky test: `Profiler_SingleProfile_Works`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3010]
https://github.com/getsentry/sentry-dotnet/actions/runs/7417484541/job/20184045406?pr=3005#step:14:445

```
[xUnit.net 00:00:12.11]     Sentry.Profiling.Tests.SamplingTransactionProfilerTests.Profiler_SingleProfile_Works(startTimeoutSeconds: 10) [FAIL]

Error: Expected sample.Timestamp to be between 0UL and 5003543400UL, but found 5005661160UL.

  Failed Sentry.Profiling.Tests.SamplingTransactionProfilerTests.Profiler_SingleProfile_Works(startTimeoutSeconds: 10) [5 s]
  Error Message:
   Expected sample.Timestamp to be between 0UL and 5003543400UL, but found 5005661160UL.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Numeric.NumericAssertions`2.BeInRange(T minimumValue, T maximumValue, String because, Object[] becauseArgs)
   at Sentry.Profiling.Tests.SamplingTransactionProfilerTests.ValidateProfile(SampleProfile profile, UInt64 maxTimestampNs) in /home/runner/work/sentry-dotnet/sentry-dotnet/test/Sentry.Profiling.Tests/SamplingTransactionProfilerTests.cs:line 64
   at Sentry.Profiling.Tests.SamplingTransactionProfilerTests.CaptureAndValidate(ITransactionProfilerFactory factory) in /home/runner/work/sentry-dotnet/sentry-dotnet/test/Sentry.Profiling.Tests/SamplingTransactionProfilerTests.cs:line 113
   at Sentry.Profiling.Tests.SamplingTransactionProfilerTests.Profiler_SingleProfile_Works(Int32 startTimeoutSeconds) in /home/runner/work/sentry-dotnet/sentry-dotnet/test/Sentry.Profiling.Tests/SamplingTransactionProfilerTests.cs:line 138
  Standard Output Messages:
 [Debug 00:00:00.32]: Starting a sampling profiler.
 [Debug 00:00:00.32]: Sleeping... time remaining: 5000 ms
 [Debug 00:00:01.32]: Sleeping... time remaining: 4000 ms
 [Debug 00:00:02.32]: Sleeping... time remaining: 3000 ms
 [Debug 00:00:03.32]: Sleeping... time remaining: 2000 ms
 [Debug 00:00:04.32]: Sleeping... time remaining: 1000 ms
 [Debug 00:00:05.32]: Profiling stopped on transaction finish.
 [Debug 00:00:05.41]: Profiler has been stopped and has received all the samples up to the end time.

```

**Comment by bruno-garcia** [comment]
Dupe of:
* https://github.com/getsentry/sentry-dotnet/issues/3006
