### ISSUE TITLE
iOS Device Tests are flaky

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#3095]
I've bumped into this a couple of times now (e.g. [here](https://github.com/getsentry/sentry-dotnet/actions/runs/7706815437/job/21003053269?pr=3094))

> device-test.ps1: The property 'FullName' cannot be found on this object. Verify that the property exists.

Rerunning the test it goes away.

Here's a bit more context from the logs:
```
2024-01-30T05:45:18.6750380Z ##[group]Run actions/download-artifact@v4
2024-01-30T05:45:18.6751650Z with:
2024-01-30T05:45:18.6752410Z   name: device-test-ios
2024-01-30T05:45:18.6753530Z   path: bin/Sentry.Maui.Device.TestApp.app
2024-01-30T05:45:18.6755240Z   merge-multiple: false
2024-01-30T05:45:18.6756350Z   repository: getsentry/sentry-dotnet
2024-01-30T05:45:18.6757540Z   run-id: 7706815437
2024-01-30T05:45:18.6758350Z env:
2024-01-30T05:45:18.6759160Z   DOTNET_CLI_TELEMETRY_OPTOUT: 1
2024-01-30T05:45:18.6761070Z   DOTNET_NOLOGO: 1
2024-01-30T05:45:18.6762180Z ##[endgroup]
2024-01-30T05:45:19.1217270Z Downloading single artifact
2024-01-30T05:45:19.3380540Z Preparing to download the following artifacts:
2024-01-30T05:45:19.3382310Z - device-test-ios (ID: 1204623102, Size: 24049193)
2024-01-30T05:45:19.4612290Z Redirecting to blob download url: https://productionresultssa3.blob.core.windows.net/actions-results/7452accf-0f5c-4e2d-9b81-5389a8dd4e21/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/artifacts/205a12c860bbe42e2caf55a54650d03bc4c2b96366f5dc46406e3ead5c04b5f1.zip
2024-01-30T05:45:19.4621120Z Starting download of artifact to: /Users/runner/work/sentry-dotnet/sentry-dotnet/bin/Sentry.Maui.Device.TestApp.app
2024-01-30T05:45:19.6616090Z (node:4567) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2024-01-30T05:45:19.6621750Z (Use `node --trace-deprecation ...` to show where the warning was created)
2024-01-30T05:45:22.2843460Z Artifact download completed successfully.
2024-01-30T05:45:22.2846890Z Total of 1 artifact(s) downloaded
2024-01-30T05:45:22.2864520Z Download artifact has finished successfully
2024-01-30T05:45:22.3298870Z ##[group]Run pwsh scripts/device-test.ps1 ios -Run
2024-01-30T05:45:22.3300380Z [36;1mpwsh scripts/device-test.ps1 ios -Run[0m
2024-01-30T05:45:22.3534910Z shell: /bin/bash -e {0}
2024-01-30T05:45:22.3535610Z env:
2024-01-30T05:45:22.3536180Z   DOTNET_CLI_TELEMETRY_OPTOUT: 1
2024-01-30T05:45:22.3536970Z   DOTNET_NOLOGO: 1
2024-01-30T05:45:22.3537520Z ##[endgroup]
2024-01-30T05:45:28.8186290Z Skipping NuGet package signature verification.
2024-01-30T05:45:31.0567510Z You can invoke the tool using the following command: xharness
2024-01-30T05:45:31.0588020Z Tool 'microsoft.dotnet.xharness.cli' (version '1.0.0-prerelease.23252.4') was successfully installed.
2024-01-30T05:45:31.7014710Z [1.0.0-prerelease.23252.4+d4d9f33ac28fe4680c3c4d12ce69a1a44d6f6b20] XHarness command issued: apple test --app bin/Sentry.Maui.Device.TestApp.app --target ios-simulator-64 --launch-timeout 00:10:00 --output-directory=test_output
2024-01-30T05:45:31.9781270Z [40m[32minfo[39m[22m[49m: Preparing run for ios-simulator-64
2024-01-30T05:45:32.0087750Z [40m[32minfo[39m[22m[49m: Looking for available ios-simulator-64 simulators..
2024-01-30T05:45:53.1636690Z [40m[32minfo[39m[22m[49m: Found simulator device 'iPhone X (iOS 16.2) - created by XHarness'
2024-01-30T05:45:53.1695330Z [40m[32minfo[39m[22m[49m: Getting app bundle information from '/Users/runner/work/sentry-dotnet/sentry-dotnet/bin/Sentry.Maui.Device.TestApp.app'..
2024-01-30T05:45:53.3384090Z [40m[32minfo[39m[22m[49m: Uninstalling any previous instance of 'io.sentry.dotnet.maui.device.testapp' from 'iPhone X (iOS 16.2) - created by XHarness'
2024-01-30T05:45:54.8306930Z [40m[32minfo[39m[22m[49m: Installing application 'Sentry.Maui.Device.TestApp' on 'iPhone X (iOS 16.2) - created by XHarness'
2024-01-30T05:50:41.5671150Z [40m[32minfo[39m[22m[49m: Application 'Sentry.Maui.Device.TestApp' was installed successfully on 'iPhone X (iOS 16.2) - created by XHarness'
2024-01-30T05:50:41.7258180Z [40m[32minfo[39m[22m[49m: Starting test run for io.sentry.dotnet.maui.device.testapp..
2024-01-30T06:00:32.1713520Z [41m[30mfail[39m[22m[49m: Run timed out after 900 seconds
2024-01-30T06:01:03.4355340Z [41m[30mfail[39m[22m[49m: Application test run crashed
2024-01-30T06:01:03.4356590Z       No test log file was produced
2024-01-30T06:01:03.4357500Z       
2024-01-30T06:01:03.4358450Z       Check logs for more information
2024-01-30T06:01:03.4360550Z [40m[32minfo[39m[22m[49m: Uninstalling the application 'io.sentry.dotnet.maui.device.testapp' from 'iPhone X (iOS 16.2) - created by XHarness'
2024-01-30T06:01:07.7937380Z [40m[32minfo[39m[22m[49m: Application 'io.sentry.dotnet.maui.device.testapp' was uninstalled successfully
2024-01-30T06:01:07.8936860Z XHarness exit code: 80 (APP_CRASH)
2024-01-30T06:01:12.1255560Z [31;1mdevice-test.ps1: [31;1mThe property 'FullName' cannot be found on this object. Verify that the property exists.[0m
2024-01-30T06:01:12.3803690Z ##[error]Process completed with exit code 1.
2024-01-30T06:01:12.4307910Z ##[group]Run pwsh scripts/device-test.ps1 ios -Run
```

**Comment by bitsandfoxes** [comment]
I've run into `Sentry.Tests.MetricAggregatorTests.GetFlushableBuckets_IsThreadsafe` [here](https://github.com/getsentry/sentry-dotnet/actions/runs/7725080445)
```
Expected value to be 100000, but found 99961 (difference of -39).
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[FluentAssertions.Numeric.NumericAssertions`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], FluentAssertions, Version=6.12.0.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a]].Be(Int32 expected, String because, Object[] becauseArgs)
   at Sentry.Tests.MetricAggregatorTests.GetFlushableBuckets_IsThreadsafe()
--- End of stack trace from previous location ---
```

**Comment by jamescrosswell** [comment]
> I've run into flaky `Sentry.Tests.MetricAggregatorTests.GetFlushableBuckets_IsThreadsafe` [here](https://github.com/getsentry/sentry-dotnet/actions/runs/7725080445)

That sounds like a different issue - there might be a genuine concurrency problem there. I've created a new issue for that.

**Comment by jamescrosswell** [comment]
This is getting worse and worse - had to rerun it twice to get it to pass on this branch:

<img width="938" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/728212/3e00674a-c2cf-4615-88e9-5d9604df946a">

We could do that automatically (retry upto max n times) knowing that it's likely to fail at least once or twice.

**Comment by jamescrosswell** [comment]
We could probably get some more information if we uploaded the logs as an artefact. I think the logs that are being referred to in the error message:
```
2024-01-30T06:01:03.4356590Z       No test log file was produced
2024-01-30T06:01:03.4357500Z       
2024-01-30T06:01:03.4358450Z       Check logs for more information
```


...are the [two log files referenced here](https://github.com/dotnet/xharness?tab=readme-ov-file#examples).

So we could check if the exit code is `-ne 0` and, if so, upload those log files as artefacts of the build that we can inspect.
