### ISSUE TITLE
Sentry.Tests.MetricAggregatorTests.GetFlushableBuckets_IsThreadsafe fails periodically in CI

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#3102]
I've run into flaky `Sentry.Tests.MetricAggregatorTests.GetFlushableBuckets_IsThreadsafe` [here](https://github.com/getsentry/sentry-dotnet/actions/runs/7725080445)
```
Expected value to be 100000, but found 99961 (difference of -39).
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[FluentAssertions.Numeric.NumericAssertions`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], FluentAssertions, Version=6.12.0.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a]].Be(Int32 expected, String because, Object[] becauseArgs)
   at Sentry.Tests.MetricAggregatorTests.GetFlushableBuckets_IsThreadsafe()
--- End of stack trace from previous location ---
```

_Originally posted by @bitsandfoxes in https://github.com/getsentry/sentry-dotnet/issues/3095#issuecomment-1919145090_

**Comment by bitsandfoxes** [comment]
I have not seen this in a while.
