### ISSUE TITLE
AppDomainProcessExitIntegration doesn't get unregistered when Sentry is disposed of/closed

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dotnet#3141]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

Any

### OS

Any (not platform specific)

### SDK Version

4.1.0

### Steps to Reproduce

I'm not yet sure how to reproduce this in plain .net but I'm getting this in sentry-powershell tests when setting a custom diagnostic logger. The general idea of what's happening:

1. create a custom diagnostic logger instance that collects messages to a concurrent bag.
2. start sentry with this logger
3. close sentry
4. exit the program
5. we get a null-reference **when running in CI**

The full test file that reproduces this (relies on importing the Sentry powershell module):

```pwsh
Describe 'SentrySdk' {
    It 'init respects options' {
        class TestLogger:Sentry.Infrastructure.DiagnosticLogger
        {
            TestLogger([Sentry.SentryLevel]$level) : base($level) {}

            $entries = [System.Collections.Concurrent.ConcurrentQueue[string]]::new();

            [void]LogMessage([string] $message) { $this.entries.Enqueue($message); }
        }

        $logger = [TestLogger]::new([Sentry.SentryLevel]::Debug)

        $options = [Sentry.SentryOptions]::new()
        $options.Debug = $true
        $options.Dsn = 'https://key@127.0.0.1/1'
        $options.DiagnosticLogger = $logger
        [Sentry.SentrySdk]::init($options)
        [Sentry.SentrySdk]::IsEnabled | Should -Be $true

        $logger.entries.Count | Should -BeGreaterThan 0
        [Sentry.SentrySdk]::close()
    }
}
```

### Expected Result

Closing the SDK (or disposing the handle) should unregister the onExit handler so that it's not called anymore. Alternatively, the handler could check whether the SDK was closed already.

### Actual Result

https://github.com/getsentry/sentry-powershell/actions/runs/7857351729/job/21441148698?pr=9
```
Running tests.
[+] /home/runner/work/sentry-powershell/sentry-powershell/tests/init.tests.ps1 937ms (458ms|2[19](https://github.com/getsentry/sentry-powershell/actions/runs/7857351729/job/21441148698?pr=9#step:6:20)ms)
Tests completed in 951ms
Tests Passed: 4, Failed: 0, Skipped: 0 NotRun: 0
Processing code coverage result.

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeAsMemberFunction(Object instance, Object[] args)
   at System.Management.Automation.Internal.ScriptBlockMemberMethodWrapper.InvokeHelper(Object instance, Object sessionStateInternal, Object[] args)
   at Sentry.Infrastructure.DiagnosticLogger.Log(SentryLevel logLevel, String message, Exception exception, Object[] args)
   at Sentry.Extensibility.DiagnosticLoggerExtensions.LogIfEnabled(IDiagnosticLogger logger, SentryLevel level, Exception exception, String message)
   at Sentry.Extensibility.DiagnosticLoggerExtensions.LogInfo(SentryOptions options, String message)
   at Sentry.Integrations.AppDomainProcessExitIntegration.HandleProcessExit(Object sender, EventArgs e)
   at Sentry.Internal.AppDomainAdapter.OnProcessExit(Object sender, EventArgs e)
Error: Process completed with exit code 134.
```

**Comment by vaind** [comment]
Maybe there could be an event on IHub `internal event ... OnClose;` which the integration can hook into to unregister its ProcessExit event handler.
