### ISSUE TITLE
Profiling startup failure

### ISSUE THREAD

**Issue by kanadaj** [getsentry/sentry-dotnet#3152]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0.102

### OS

Windows

### SDK Version

4.1.1

### Self-Hosted Sentry Version

24.1.2

### Steps to Reproduce

1. Install Sentry
2. Install Sentry.Profiling
3. Configure profiling as per https://docs.sentry.io/platforms/dotnet/profiling/ including the sync startup. 
4. Enable debug logging for Sentry
5. Start the app from the csproj folder with `dotnet watch` (Haven't tested if repros with `dotnet run`)

### Expected Result

Profiling should work

### Actual Result

```cs
[18:22:38 ERR] Failed to initialize the profiler
System.AggregateException: One or more errors occurred. (Could not load type 'EventPipeRundownConfiguration' from assembly 'Microsoft.Diagnostics.Tracing.TraceEvent, Version=3.1.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.)
 ---> System.TypeLoadException: Could not load type 'EventPipeRundownConfiguration' from assembly 'Microsoft.Diagnostics.Tracing.TraceEvent, Version=3.1.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Sentry.Profiling.SampleProfilerSession.StartNew(IDiagnosticLogger logger)
   at Sentry.Profiling.SamplingTransactionProfilerFactory.<>c__DisplayClass7_0.<<-ctor>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Sentry.Profiling.SamplingTransactionProfilerFactory..ctor(SentryOptions options, TimeSpan startupTimeout)
   at Sentry.Profiling.ProfilingIntegration.Register(IHub hub, SentryOptions options)
[18:22:38 WRN] You've tried to enable profiling in options, but it is not available, because ProfilingIntegration from package Sentry.Profiling hasn't been registered. You can do that by calling 'options.AddIntegration(new ProfilingIntegration())'.
```

**Comment by kanadaj** [comment]
Update: I think removing the NuGet dependency for Microsoft.Diagnostics.Tracing.TraceEvent might have fixed this? I'm unsure why if so.
