### ISSUE TITLE
`GetFlushableBuckets_IsThreadsafe` failed on CI

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3290]
https://github.com/getsentry/sentry-dotnet/actions/runs/8663102444/attempts/1

Failed on iOS only

```
Expected value to be 100000, but found 99972 (difference of -28).
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[FluentAssertions.Numeric.NumericAssertions`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], FluentAssertions, Version=6.12.0.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a]].Be(Int32 expected, String because, Object[] becauseArgs)
   at Sentry.Tests.MetricAggregatorTests.GetFlushableBuckets_IsThreadsafe()
--- End of stack trace from previous location ---
```

**Comment by bruno-garcia** [comment]
Or maybe its' not thread safe O_O

**Comment by jamescrosswell** [comment]
> Or maybe its' not thread safe O_O

Yeah that was the point of the test...

**Comment by jamescrosswell** [comment]
Closing this as Metrics is being deprecated (along with this test)
