### ISSUE TITLE
Sentry.Maui package causes Unhandled Exception in .NET MAUI WinUI application

### ISSUE THREAD

**Issue by luminixinc** [getsentry/sentry-dotnet#3706]
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

8.0

### OS

Windows

### SDK Version

4.12.1

### Steps to Reproduce

We have created a reduced test case that demonstrates the problem. See https://github.com/luminixinc/NetMauiWinUI_SentryMaui

### Expected Result

I expected to be able to run the simple application and see the MainPage with waving dotnet bot and the extra button that calls `SentrySdk.CaptureMessage`

### Actual Result

Unhandled exception {"Could not load file or assembly 'WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'. The system cannot find the file specified.":"WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709"}

See reduced test case that demonstrates the issue at https://github.com/luminixinc/NetMauiWinUI_SentryMaui

**Comment by bricefriha** [comment]
@luminixinc thanks for reporting this.

I ran the app from the repo you provided. Unfortunately, I'm unable to reproduce the issue.
I can run the app, click the button, and see the message captured on Sentry without exception.
![Image](https://github.com/user-attachments/assets/c2543d1d-a11f-4d87-aec4-03cd3b404ec7)

I tried with both our DSN and yours (you should be able to see the item on the issues tab on Sentry on your hand as well).  

>Unhandled exception {"Could not load file or assembly 'WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'. The system cannot find the file specified.":"WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709"}

Additionally, this message indicates that WinRT.Runtime is missing. So, it's unlikely related to the Sentry SDK.

Is there any other info that would help reproduce this issue?

**Comment by CyborgDE** [comment]
Hello,
I have the same issue with Versions greater 4.12.0.
4.12.0 is OK ...

**Comment by bricefriha** [comment]
Thanks @CyborgDE 

I'm gonna investigate further, especially on 4.12.1; if it's on this version, it may be related to #3655 according to the change logs

**Comment by jamescrosswell** [comment]
> Thanks [@CyborgDE](https://github.com/CyborgDE)
> 
> I'm gonna investigate further, especially on 4.12.1; if it's on this version, it may be related to [#3655](https://github.com/getsentry/sentry-dotnet/pull/3655) according to the change logs

I don't think that change is related. `WinRT.Runtime` doesn't have anything to do with `Utf8JsonWriter`.

**Comment by rogerbriggen-securiton** [comment]
We have the same issue. It seems that Sentry has a dependency to WinRT.Runtime 2.1 but on my dev machine with latest Visual Studio and lastest Visual Studio Preview I only have 1.6 of WindowsAppRuntime.
Checked with 
get-appxpackage *appruntime*


2024-11-28 15:50:03.277 +01:00 [ERR]  Unhandled exception. Sender: Redacted.WinUI.App UnhandledExceptionEventArgs: System.UnhandledExceptionEventArgs { ThreadId: 1 }
System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'. The system cannot find the file specified.
File name: 'WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'
   at WinRT.Sentry_MauiGenericHelpers.GlobalVtableLookup.InitializeGlobalVtableLookup()
   at .cctor()
   --- End of inner exception stack trace ---
   at Redacted.MauiProgram.SetupSentry(MauiAppBuilder builder)
   at Redacted.MauiProgram.CreateMauiApp() in C:\git\redacted\MauiProgram.cs:line 53
   at Redacted.WinUI.App.CreateMauiApp() in C:\git\redacted\Platforms\Windows\App.xaml.cs:line 24
   at Microsoft.Maui.MauiWinUIApplication.OnLaunched(LaunchActivatedEventArgs args)
   at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)

**Comment by bruno-garcia** [comment]
Sentry doesn't really have any dependencies. [`Sentry.Maui` depends](https://www.nuget.org/packages/Sentry.Maui/5.0.0-alpha.1#dependencies-body-tab) on [`Sentry.Extensions.Logging` 
Which depends](https://www.nuget.org/packages/Sentry.Extensions.Logging/#dependencies-body-tab) on `Sentry` which has no dependencies.

S.E.L also depends on `Microsoft.Extensions.Http`, `Microsoft.Extensions.Logging.Configuration` and `Microsoft.Extensions.Configuration.Binder` (on net8+)

**Comment by rogerbriggen-securiton** [comment]
> Sentry doesn't really have any dependencies. [`Sentry.Maui` depends](https://www.nuget.org/packages/Sentry.Maui/5.0.0-alpha.1#dependencies-body-tab) on [`Sentry.Extensions.Logging` Which depends](https://www.nuget.org/packages/Sentry.Extensions.Logging/#dependencies-body-tab) on `Sentry` which has no dependencies.
> 
> S.E.L also depends on `Microsoft.Extensions.Http`, `Microsoft.Extensions.Logging.Configuration` and `Microsoft.Extensions.Configuration.Binder` (on net8+)

Nuget wise you are right. But I guess you used 8.0.404 to compile your MAUI nuget and there are dependencies.
It does not crash on my side, wenn I use 8.0.404 to compile my version, then it works with Sentry 4.13. With 8.0.401 it crashes, there a downgrade to 4.12 helps.
And you get the dependencies from here: https://github.com/dotnet/maui/issues/25132

**Comment by jamescrosswell** [comment]
> Nuget wise you are right. But I guess you used 8.0.404 to compile your MAUI nuget and there are dependencies.
> It does not crash on my side, wenn I use 8.0.404 to compile my version, then it works with Sentry 4.13. With 8.0.401 it crashes, there a downgrade to 4.12 helps.

We had to bump to at least 8.0.403 for folks using Xcode 16.x.

I'm surprised downgrading to 4.12 helps however, as that [change was made in the 4.12 release](https://github.com/getsentry/sentry-dotnet/blob/main/CHANGELOG.md#support-for-xcode-160-breaking-change). @bruno-garcia I'm wondering whether there's an issue with the changelog - perhaps that workload was used to build the 4.12.1 release (not the 4.12.0 release)? I vaguely remember some issues with the build when we made that release.

In any event, if you're using Sentry 4.12+ then you need to be using version 8.0.403 or later of the MAUI workloads.

**Comment by alexsohn1126** [comment]
Since the issue was related to .NET 8.0.403 vs. 401, this issue can be solved by upgrading .NET. Since .NET 10 is coming out this November, this issue seems irrelevant.
