### ISSUE TITLE
Sentry.Tests.HubTests.FlushOnDispose_SendsEnvelope Flaky on iOS

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#3765]
E.g. [this build run](https://github.com/getsentry/sentry-dotnet/actions/runs/11882078266?pr=3725):
```
Sentry.Tests.dll
Sentry.Tests.HubTests.FlushOnDispose_SendsEnvelope(cachingEnabled: True) - Failed
NSubstitute.Exceptions.ReceivedCallsException : Expected to receive exactly 1 call matching:
	SendEnvelopeAsync(any Envelope, any CancellationToken)
Actually received no matching calls.
at NSubstitute.Core.ReceivedCallsExceptionThrower.Throw(ICallSpecification callSpecification, IEnumerable`1 matchingCalls, IEnumerable`1 nonMatchingCalls, Quantity requiredQuantity)
   at NSubstitute.Routing.Handlers.CheckReceivedCallsHandler.Handle(ICall call)
   at NSubstitute.Routing.Route.Handle(ICall call)
   at NSubstitute.Core.CallRouter.Route(ICall call)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleForwardingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at NSubstitute.Proxies.CastleDynamicProxy.ProxyIdInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy_5.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken)
   at Sentry.Tests.HubTests.FlushOnDispose_SendsEnvelope(Boolean cachingEnabled)
--- End of stack trace from previous location ---
```

**Comment by jamescrosswell** [comment]
We haven't seen these in a while so closing for now.
