### ISSUE TITLE
System.BadImageFormatException: Read out of bounds.

### ISSUE THREAD

**Issue by shyn** [getsentry/sentry-dotnet#3859]
I used sentry with aspnetcore.

nuget package: Sentry.AspNetCore 4.13.0
aspnetcore version: 9.0.0

build for linux on macos with `dotnet publish -r linux-x64 --self-contained true`

When ran on linux. I got:

```console
fail: Sentry.ISentryClient[0]
      An error occurred when capturing the event 415604de8abd444ebbbf46aac8003485.
      System.BadImageFormatException: Read out of bounds.
         at System.Reflection.Throw.OutOfBounds()
         at System.Reflection.Metadata.Ecma335.MethodDebugInformationTableReader.GetSequencePoints(MethodDebugInformationHandle handle)
         at System.Reflection.Metadata.MethodDebugInformation.GetSequencePoints()
         at System.Diagnostics.Internal.PortablePdbReader.PopulateStackFrame(StackFrame frameInfo, MethodBase method, Int32 IlOffset, String& fileName, Int32& row, Int32& column)
         at System.Diagnostics.EnhancedStackTrace.GetFrames(StackTrace stackTrace)
         at Sentry.Internal.DebugStackTrace.CreateFrames(StackTrace stackTrace, Boolean isCurrentStackTrace, Func`2 skipFrame)+MoveNext()
         at System.Linq.Enumerable.<ToArray>g__EnumerableToArray|314_0[TSource](IEnumerable`1 source)
         at System.Linq.Enumerable.ReverseIterator`1.MoveNext()
         at Sentry.Internal.DebugStackTrace.Create(SentryOptions options, StackTrace stackTrace, Boolean isCurrentStackTrace, Func`2 skipFrame)
         at Sentry.Internal.DebugStackTrace.Create(SentryOptions options, StackTrace stackTrace, Boolean isCurrentStackTrace, Int32 skipFrames)
         at Sentry.Extensibility.SentryStackTraceFactory.Create(Exception exception)
         at Sentry.Internal.MainSentryEventProcessor.Process(SentryEvent event)
         at Sentry.Extensibility.ISentryEventProcessorExtensions.DoProcessEvent(ISentryEventProcessor processor, SentryEvent event, SentryHint hint)
         at Sentry.SentryClient.DoSendEvent(SentryEvent event, SentryHint hint, Scope scope)
         at Sentry.SentryClient.CaptureEvent(SentryEvent event, Scope scope, SentryHint hint)
```

What can be wrong? I don't understand it's all dotnet dll assemblies right? How BadImageFormatException came out?

**Comment by jamescrosswell** [comment]
Hi @shyn ,

When Sentry captures an error it tries to load debug information from the PDB file, which I think is what's happening here:
```
at System.Diagnostics.Internal.PortablePdbReader.PopulateStackFrame(StackFrame frameInfo, MethodBase method, Int32 IlOffset, String& fileName, Int32& row, Int32& column)
```

It seems to be failing when trying to read the `MethodDebugInformation` though.

If you've got a small sample app that you can share, which demonstrates the problem, that would help. Otherwise I can try to reproduce here but it may be a while before I can find the time for this.

**Comment by bruno-garcia** [comment]
Not sure why this is happening, it's as if you built for Linux x64 but somehow there's some native x32 binaries somewhere there instead? Just guessing.

The error happens when trying to build 'pretty looking' stack traces. Which with do with [Ben.Demustifier](https://github.com/getsentry/Ben.Demystifier). You can work around that by setting it to Mode Original:

https://github.com/getsentry/sentry-dotnet/blob/9529c1dd839e159bc105fcca72c3167e6e66aeb8/src/Sentry/StackTraceMode.cs#L11-L17

**Comment by shyn** [comment]
thanks @bruno-garcia @jamescrosswell for the information. I will dig later. Happy holiday by the way.
