### ISSUE TITLE
Sentry.Samples.NLog does not work with the NLog configuration file

### ISSUE THREAD

**Issue by timemaster67** [getsentry/sentry-dotnet#403]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ x] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [ x] .NET Core

* Version:2.1.2-beta4

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ x] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version:2.1.2-beta4

Take the current git version and run the sentry-dotnet\samples\Sentry.Samples.NLog program
If you use the UsingCodeConfiguration, everything works fine
if you use the UsingNLogConfigFile, sending errors to Sentry does not work and nlog also does not work. This failure is silent because by default NLog does not throw exception. You can see that NLog does not work because nothing is written to the console. LogInfo, Errors and etc should all be written to the console as it's one of the target. 

Modify the nlog.config file and at the top of the file, replace the <nlog> tag with this one
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true"
      throwConfigExceptions="true"

NLog will throw that 
NLog.NLogConfigurationException: Exception when parsing \sentry-dotnet\samples\Sentry.Samples.NLog\bin\Debug\netcoreapp2.1\NLog.config.  ---> System.NotSupportedException: Parameter value not supported on TargetPropertyWithContext
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.AddArrayItemFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.SetPropertyFromElement(Object o, NLogXmlElement element)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors, LogFactory logFactory)
   at NLog.LogFactory.LoadXmlLoggingConfiguration(String configFile)
   at NLog.LogFactory.TryLoadLoggingConfiguration(String configFile, LoggingConfiguration& config)
   at NLog.LogFactory.TryLoadFromFilePaths()
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name)
   at NLog.LogManager.GetCurrentClassLogger()
   at Sentry.Samples.NLog.Program.UsingNLogConfigFile() in \sentry-dotnet\samples\Sentry.Samples.NLog\Program.cs:line 93
   at Sentry.Samples.NLog.Program.Main(String[] args) in \sentry-dotnet\samples\Sentry.Samples.NLog\Program.cs:line 24

If you remove these two lines from your sentry target
 <tag name="exception" value="${exception:format=shorttype}" includeEmptyValue="false" />
  <contextproperty name="threadid" value="${threadid}" includeEmptyValue="true" />

then nlog will work correctly and sentry will also work correctly. 

Please either correct your sample to reflect the new configuration layout, or correct your Sentry.NLog to support the configuration you have written in your sample file. 
Thank you.

**Comment by snakefoot** [comment]
Created #404 to resolve this.
