### ISSUE TITLE
Flaky test: CachingTransportTests.AwareOfExistingFiles

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#608]
```
Error: Sentry.Tests.Internals.Http.CachingTransportTests.AwareOfExistingFiles: Expected innerTransport.GetSentEnvelopes() to contain 3 item(s), but found 2.
  Failed Sentry.Tests.Internals.Http.CachingTransportTests.AwareOfExistingFiles [5 s]
  Error Message:
   Expected innerTransport.GetSentEnvelopes() to contain 3 item(s), but found 2.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Collections.SelfReferencingCollectionAssertions`2.HaveCount(Int32 expected, String because, Object[] becauseArgs)
   at Sentry.Tests.Internals.Http.CachingTransportTests.<AwareOfExistingFiles>d__3.MoveNext() in D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\Internals\Http\CachingTransportTests.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Sentry.Tests.Internals.Http.CachingTransportTests.<AwareOfExistingFiles>d__3.MoveNext() in D:\a\sentry-dotnet\sentry-dotnet\test\Sentry.Tests\Internals\Http\CachingTransportTests.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by bruno-garcia** [comment]
This one failed 2 or 3 times in a row so sounds like an actual problem
