### ISSUE TITLE
Incompatible with Serilog.AspNetCore

### ISSUE THREAD

**Issue by Mitch528** [getsentry/sentry-dotnet#67]
I'm not sure if this is an issue that would need to be fixed on the side of [serilog/serilog-aspnetcore](https://github.com/serilog/serilog-aspnetcore) or sentry, but currently they cannot be used together.

The following code results in an exception on startup:
```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseSentry()
        .UseSerilog();
```

```
λ dotnet run
Using launch settings from C:\Users\Mitchell\source\repos\WebApplication4\WebApplication4\Properties\launchSettings.json...
Application startup exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sentry.SentryOptionsExtensions.AddEventProcessorProvider(SentryOptions options, Func`1 processorProvider) in C:\projects\sentry-dotnet\src\Sentry\SentryOptionsExtensions.cs:line 80
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseServiceProviderProcessors(IServiceProvider provider) in C:\projects\sentry-dotnet\src\Sentry.AspNetCore\ApplicationBuilderExtensions.cs:line 37
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseSentry(IApplicationBuilder app) in C:\projects\sentry-dotnet\src\Sentry.AspNetCore\ApplicationBuilderExtensions.cs:line 26
   at Sentry.AspNetCore.SentryStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder e) in C:\projects\sentry-dotnet\src\Sentry.AspNetCore\SentryStartupFilter.cs:line 13
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sentry.SentryOptionsExtensions.AddEventProcessorProvider(SentryOptions options, Func`1 processorProvider) in C:\projects\sentry-dotnet\src\Sentry\SentryOptionsExtensions.cs:line 80
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseServiceProviderProcessors(IServiceProvider provider) in C:\projects\sentry-dotnet\src\Sentry.AspNetCore\ApplicationBuilderExtensions.cs:line 37
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseSentry(IApplicationBuilder app) in C:\projects\sentry-dotnet\src\Sentry.AspNetCore\ApplicationBuilderExtensions.cs:line 26
   at Sentry.AspNetCore.SentryStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder e) in C:\projects\sentry-dotnet\src\Sentry.AspNetCore\SentryStartupFilter.cs:line 13
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at WebApplication4.Program.Main(String[] args) in C:\Users\Mitchell\source\repos\WebApplication4\WebApplication4\Program.cs:line 18
```

**Comment by bruno-garcia** [comment]
Hi @Mitch528 

This commit #65 fixed the null ref exception but essentially the SDK is disabled at that point if used with Serilog.
Serilog simply disables our `LoggingProvider`.

I'm investigating if we can get them to work together or we'll need to use a Serilog Sink which anyway we plan to build.

Thanks for reporting this error,

**Comment by bruno-garcia** [comment]
Pretty much this: https://github.com/serilog/serilog-aspnetcore/issues/3

**Comment by bruno-garcia** [comment]
@Mitch528  A new version with the fix was published:

https://github.com/getsentry/sentry-dotnet/releases/tag/0.0.1-preview4

Thanks again for helping trying it out and reporting!

**Comment by Mitch528** [comment]
@bruno-garcia Great, thanks!

**Comment by bruno-garcia** [comment]
If you are using on prem please note the last release doesn't work if you don't have nginx or something which supports chunked requests. You have disabled gzip requests to work around it. Master has it fixed and it will be on nuget soon when we publish preview5
