### ISSUE TITLE
 System.Text.Json.JsonReaderException when Sending large ZIP Attachments

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#688]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [x] Xamarin
- [x] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [x] Mono
- [x] .NET Core

* Version:

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version:

Console app shows an error on Sentry debug Logger on files larger than 25MB, while on Xamarin Forms, it crashes the app on Android 5.0 while on Android 10 Another error pattern happens, but for now, I think it's better to focus on the Sample below since everyone is able to reproduce i.

Error Stacktrace
```
Error: Error while processing event 7988453045684afa8778d03232cd01e7: System.Text.Json.JsonReaderException: 'R' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 4.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at Sentry.Internal.Extensions.HttpClientExtensions.ReadAsJsonAsync(HttpContent content, CancellationToken cancellationToken) in C:\xx\SentrySdk\OfficialNet\src\Sentry\Internal\Extensions\HttpClientExtensions.cs:line 15
   at Sentry.Internal.Http.HttpTransport.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken) in C:\Users\xx\SentrySdk\OfficialNet\src\Sentry\Internal\Http\HttpTransport.cs:line 117
```
Sample code:

```csharp
using Sentry;

static class Program
{
    static void Main()
    {
        SentrySdk.Init( options => {
            options.Dsn = "https://80aed643f81249d4bed3e30687b310ab@o447951.ingest.sentry.io/5428537";
            options.Debug = true;
            });

        System.Console.WriteLine("\n                 26MB File");
        SentrySdk.WithScope((scope) =>
        {
            scope.AddAttachment("../../../lifeforce_by_andromeda_software_development.zip");
            SentrySdk.CaptureMessage("Hello World");
        });
        System.Console.ReadKey();

        System.Console.WriteLine("\n                 2MB File");
        SentrySdk.WithScope((scope) =>
        {
            scope.AddAttachment("../../../2nd_real.zip");
            SentrySdk.CaptureMessage("Hello World");
        });
        System.Console.ReadKey();

        System.Console.WriteLine("\n14MB File");
        SentrySdk.WithScope((scope) =>
        {
            scope.AddAttachment("../../../fr-055_828_final.zip");
            SentrySdk.CaptureMessage("\n                 Hello World");
        });
        System.Console.ReadKey();

        System.Console.WriteLine("\n                 41MB File");
        SentrySdk.WithScope((scope) =>
        {
            scope.AddAttachment("../../../crass-phase_one.zip");
            SentrySdk.CaptureMessage("Hello World");
        });
        System.Console.ReadKey();
    }
}

```

Files used:
26MB https://files.scene.org/view/parties/2007/assembly07/demo/lifeforce_by_andromeda_software_development.zip
2MB https://files.scene.org/view/parties/1993/assembly93/demo/2nd_real.zip
14MB http://www.farbrausch.de/~fg/demos/fr-055_828_final.zip
41MB https://files.scene.org/view/parties/2008/syntax08/demo/crass-phase_one.zip

**Comment by lucas-zimerman** [comment]
Edit: I cannot send large files, near to 50MB  due to timeout (Unless I have Korean internet to make a single post with 50MB on the body haha)
sample file: https://www.mediafire.com/file/klfxsdjcr1n5e83/starcraft.mp4/file
