### ISSUE TITLE
Calling .UseSentryTracing() before .UseEndpoints() destroys ASP.NET exception handling

### ISSUE THREAD

**Issue by Zero3** [getsentry/sentry-dotnet#805]
SDK: Sentry.AspNetCore 3.0.3

Calling `.UseSentryTracing()` before `.UseEndpoints()` in `Configure()` causes the ASP.NET exception handling flow to be messed up.

## Expected behaviour

Throwing an exception from an ASP.NET Core controller works normally, i.e. causes a HTTP 500 response to be returned, and any attached exception handler (`.UseExceptionHandler()`) will be triggered in the process.

## Actual behaviour

Sentry somehow swallows the exception and causes an empty HTTP 200 (!) response to be returned. Additionally, any attached exception handler is not triggered in the process.

## Workaround

Move the call to `.UseSentryTracing()` after `.UseEndpoints()` in `Configure()`.

**Comment by kanadaj** [comment]
It's not UseEndpoints that the tracing middleware needs but UseRouting().

The middleware won't do much if you place it _after_ `.UseEndpoints()` because `.UseEndpoints()` doesn't forward the request to the next middleware unless it's unhandled.

There is probably an exception thrown inside `SentryMiddleware` which is causing this. Do you have a stacktrace in the logs? Might even have 2 stacktraces instead of 1 due to Sentry also throwing.

**Comment by Tyrrrz** [comment]
To enable logging in Sentry, do this:

```csharp
.UseSentry(options =>
{
    options.Debug = true;
    options.DiagnosticLevel = DiagnosticLevel.Debug;
}
```

This should give additional information as to what happened.

**Comment by Zero3** [comment]
@kanadaj Aha, that explains why my "workaround" stops the problem, as it indirectly disables the tracing middleware. I was not aware of that behaviour of `.UseEndpoints()`, but it makes sense.

It would be nice if the correct location to place `.UseSentryTracing()` was documented somewhere (at least I couldn't find anything about this).

Also, if Sentry fails internally for some reason, I think it should back off gracefully instead of destroying the ASP.NET exception flow.

@kanadaj @Tyrrrz Thanks for the debugging suggestions. I enabled the debug logging, and this is what gets logged when I trigger an exception from a controller (the log format is custom for my system):

````
[Sentry.ISentryClient] New scope pushed.
[Sentry.ISentryClient] New scope pushed.
[Sentry.ISentryClient] New scope pushed.
[Sentry.ISentryClient] Configuring the scope.
[Sentry.ISentryClient] Configuring the scope.
[Sentry.ISentryClient] Configuring the scope asynchronously.
[Sentry.ISentryClient] Started transaction: Span ID: c47c04e479f14841, Trace ID: cac2a778a04a458a8decc990fdd40691
[Sentry.ISentryClient] Configuring the scope.
[Sentry.ISentryClient] Locked scope. No new scope pushed.
<logging by my controller code here>
[Sentry.ISentryClient] Configuring the scope.
[Sentry.ISentryClient] Transaction dropped by sampling.
[Sentry.ISentryClient] Locked scope. No new scope pushed.
[Sentry.ISentryClient] Failure to ConfigureScopeAsync   
<stack trace of the exception thrown by my controller here>
[Sentry.ISentryClient] Configuring the scope.
[Sentry.ISentryClient] Disposing scope.
[Sentry.ISentryClient] Disposing scope.
````

The only line of interest seems to be this one, which is logged with warning level:

````
[Sentry.ISentryClient] Failure to ConfigureScopeAsync   
````

**Comment by Zero3** [comment]
It does indeed seem like Sentry is swallowing the exception here: https://github.com/getsentry/sentry-dotnet/blob/a757f981a8197215a28de038f318cae0ad313b07/src/Sentry/Internal/Hub.cs#L70-L80

I am not sure whether it is correct that this method wraps the execution of the underlying controller code though? By the name, this method sounds more like something that should run before executing the controller code. But this is just guesswork from my side, as I do not know anything about the internals of the SDK.

Also, I fired up a debugger, and captured this stack trace of the exception throw inside my application code, which shows the path through the `ConfigureScopeAsync()` with the problematic `catch`:

````
   <stack frames inside my application code>
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Sentry.AspNetCore.SentryTracingMiddleware.<>c__DisplayClass5_0.<<InvokeAsync>b__0>d.MoveNext() in /_/src/Sentry.AspNetCore/SentryTracingMiddleware.cs:line 91
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.AspNetCore.SentryTracingMiddleware.<>c__DisplayClass5_0.<InvokeAsync>b__0(Scope scope)
   at Sentry.Internal.SentryScopeManager.ConfigureScopeAsync(Func`2 configureScope) in /_/src/Sentry/Internal/SentryScopeManager.cs:line 47
   at Sentry.Internal.Hub.ConfigureScopeAsync(Func`2 configureScope) in /_/src/Sentry/Internal/Hub.cs:line 82
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.Internal.Hub.ConfigureScopeAsync(Func`2 configureScope)
   at Sentry.SentrySdk.ConfigureScopeAsync(Func`2 configureScope) in /_/src/Sentry/SentrySdk.cs:line 251
   at Sentry.Extensibility.HubAdapter.ConfigureScopeAsync(Func`2 configureScope) in /_/src/Sentry/Extensibility/HubAdapter.cs:line 51
   at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context) in /_/src/Sentry.AspNetCore/SentryTracingMiddleware.cs:line 63
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context, ICorsPolicyProvider corsPolicyProvider)
   at lambda_method(Closure , Object , HttpContext , IServiceProvider )
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_1.<UseMiddleware>b__2(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context) in /_/src/Sentry.AspNetCore/SentryMiddleware.cs:line 112
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
````
