### ISSUE TITLE
Unhandled Exception in WithScope

### ISSUE THREAD

**Issue by PaitoAnderson** [getsentry/sentry-dotnet#852]
While I might have incorrectly used `WithScope` this lead to my entire web app crashing on Azure every time it tried to call Twilio. They are having a rough day: https://status.twilio.com/

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Sentry.AspNetCore @ 3.0.5

### Steps to Reproduce

```cs
var response = await _httpClient.PostAsync("Messages.json", new FormUrlEncodedContent(content));
if (response.IsSuccessStatusCode == false) {
    SentrySdk.WithScope(async scope => {
        scope.SetExtra("error", await response.Content.ReadAsStringAsync());

        response.EnsureSuccessStatusCode();
    });
}
```

### Expected Result

It would log an exception in Sentry with the response captured.

### Actual Result

It crashed my entire web app instance.

```
Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at LoadOne.Infrastructure.Services.SMS.<>c__DisplayClass2_0.<<SendMessage>b__0>d.MoveNext() in C:\projects\webapp\src\LoadOne.Infrastructure\Services\ISMS.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by bruno-garcia** [comment]
WithScope doesn't take `Func<Task>` you can't call async in it. you're basically doing `async void`.

**Comment by PaitoAnderson** [comment]
@bruno-garcia Yes, I did do that to fix this. I'll close this out then.
```cs
if (response.IsSuccessStatusCode == false)
{
    var responseContent = await response.Content.ReadAsStringAsync();
    SentrySdk.WithScope(scope =>
    {
        scope.SetExtra("Response", responseContent);
        response.EnsureSuccessStatusCode();
    });
}
```

**Comment by bruno-garcia** [comment]
The data you set to the scope there will be thrown away once the block finishes running.
What you want to do instead is:

```csharp
if (response.IsSuccessStatusCode == false)
{
    var responseContent = await response.Content.ReadAsStringAsync();
    var ex = new InvalidOperationException("Failed fetching abc", e);
    ex.Data["responseContent"] = responseContent; // Add any useful data like this
    ex.Data["sentry:tag:status"] = response.StatusCode;
    ex.Data["sentry:tag:url"] = url; // Adds a tag called URL (from the next version on 3.1.0)
    throw ex;
}
```

**Comment by PaitoAnderson** [comment]
@bruno-garcia 

Thank you for taking the time to create this example! I'll be using it.

I had also never run across `async void` and didn't realize it could crash your whole app when posting.

**Comment by bruno-garcia** [comment]
Shouldn't crash your whole app unless UnobservedTaskException is configured to crash which isn't default since dotnet 4.0

**Comment by PaitoAnderson** [comment]
This was using .NET Core 3.1. Here is an example:

```cs
using System;

namespace AsyncVoid
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                ThrowsAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Caught in try/catch  : {ex.Message}");
            }

            Console.ReadKey();
        }

        private static async void ThrowsAsync()
        {
            Console.WriteLine("Throwing...");
            throw new Exception("Boom!");
        }
    }
}
```

```
Throwing...
Unhandled exception. System.Exception: Boom!
   at AsyncVoid.Program.ThrowsAsync() in /Users/paitoanderson/Development/AsyncVoid/Program.cs:line 25
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by bruno-garcia** [comment]
Oh I would have thought that goes into the `UnobservedTaskException` [but there's a good explanation here why this is](https://stackoverflow.com/questions/53215577/why-does-exception-from-async-void-crash-the-app-but-from-async-task-is-swallowe).
