### ISSUE TITLE
Exception serializing envelope with `WriteDynamicValue`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#946]
No repro yet:

```
Exception:
System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
   at System.RuntimeType.get_DeclaringMethod()
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue& value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
   at Sentry.JsonSerializableExtensions.WriteDynamicValue(Utf8JsonWriter writer, Object value) in /_/src/Sentry/IJsonSerializable.cs:line 106
   at Sentry.SentryEvent.WriteTo(Utf8JsonWriter writer) in /_/src/Sentry/SentryEvent.cs:line 344
   at Sentry.Protocol.Envelopes.JsonSerializable.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/JsonSerializable.cs:line 27
   at Sentry.Protocol.Envelopes.JsonSerializable.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/JsonSerializable.cs:line 28
   at Sentry.Protocol.Envelopes.EnvelopeItem.BufferPayloadAsync(CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/EnvelopeItem.cs:line 64
   at Sentry.Protocol.Envelopes.EnvelopeItem.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/EnvelopeItem.cs:line 101
   at Sentry.Protocol.Envelopes.Envelope.SerializeAsync(Stream stream, CancellationToken cancellationToken) in /_/src/Sentry/Envelopes/Envelope.cs:line 66
   at Sentry.Internal.Http.EnvelopeHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context) in /_/src/Sentry/Internal/Http/EnvelopeHttpContent.cs:line 16
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at Sentry.Internal.Http.GzipBufferedRequestBodyHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/GzipBufferedRequestBodyHandler.cs:line 58
   at Sentry.Internal.Http.RetryAfterHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/RetryAfterHandler.cs:line 64
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Sentry.Internal.Http.HttpTransport.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken) in /_/src/Sentry/Internal/Http/HttpTransport.cs:line 113
   at Sentry.Internal.BackgroundWorker.WorkerAsync() in /_/src/Sentry/Internal/BackgroundWorker.cs:line 134
```

**Comment by Tyrrrz** [comment]
It's failing here: https://github.com/getsentry/sentry-dotnet/blob/49575e98544ec835fd6af1a70c97d14876461690/src/Sentry/IJsonSerializable.cs#L94-L97

Really need to know at least what type was being serialized to have a chance at troubleshooting.

**Comment by bruno-garcia** [comment]
I think we need to ignore this error. Log out with the diag logger and carry on.
We only use this on Extra and Contexts and it's better to lose that than the event.

**Comment by Tyrrrz** [comment]
Removing from v3.x because the issue is not actionable

**Comment by AndrewPearson** [comment]
One of the issues with this exception is that the call stack does not include the client code where the message was sent (in this case via a Serilog call). Without this information it is nigh on impossible for the client to know which code might be the root cause.
If it would be possible somehow to augment the exception message with more details of the client call then that would probably enable the caller to solve the issue with their code.

**Comment by AndrewPearson** [comment]
I'd also add that this issue does not occur when using version 3.0.6 of Sentry.Serilog. We first noticed the issue when we updated to 3.1.0.

**Comment by bruno-garcia** [comment]
> I'd also add that this issue does not occur when using version 3.0.6 of Sentry.Serilog. We first noticed the issue when we updated to 3.1.0.

We only added support back to serialize 'custom' objects around that so ti makes sense. Before that it was just doing `obj.ToString()`.

There's no way to tell you the stack trace of the code that set the value unless we serialize at the time of setting the instance, or get a stack trace in the setter 'just in case' there's an error, so we can report that too.

I'd say if we can at least supress the exception (you only lose the object you wanted as context, not the event), and log out some information: Key that was set in the `Extra` or `Contexts` and the `typeof()` of it, etc. Should be enough to track down where this comes from.

Somewhere, you're adding an object that can't be serialized, to a scope object. 
Something like:
```
SentrySdk.ConfigureScope(s => {
s.SetExtra("bad object", notSerializableObjectInstace);
s.Contexts["bad object"] = notSerializableObjectInstace)
});

// or if using an integration:

using (_logger.BeginScope(badObjetCantBeSerialized)) {}
```

**Comment by bruno-garcia** [comment]
There was an attempt to pull the serialization logic out of the models, so we could pass a logger instance to it, and handle this: https://github.com/getsentry/sentry-dotnet/issues/1218
