### ISSUE TITLE
Envelope serialized on unix-like can't be deserialized on Windows (tz db)

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#947]
Raised by @lucas-zimerman:

Since `FindSystemTimeZoneById` doesn't work across these platforms we need a strategy around this. Possibly dropping the typed `TimeZoneInfo` object and relying only on a String.

```
Error: Failed to send cached envelope: System.TimeZoneNotFoundException: The time zone ID 'America/Sao_Paulo' was not found on the local computer.
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at Sentry.Internal.Extensions.JsonExtensions.Pipe[TIn,TOut](TIn input, Func`2 pipe) in C:\Users\lucas\source\repos\SentrySdk\OfficialNet\src\Sentry\Internal\Extensions\JsonExtensions.cs:line 132
   at Sentry.Protocol.Device.FromJson(JsonElement json) in C:\Users\lucas\source\repos\SentrySdk\OfficialNet\src\Sentry\Protocol\Device.cs:line 341
   at Sentry.Contexts.FromJson(JsonElement json) in C:\Users\lucas\source\repos\SentrySdk\OfficialNet\src\Sentry\Protocol\Contexts.cs:line 118
   at Sentry.Internal.Extensions.JsonExtensions.Pipe[TIn,TOut](TIn input, Func`2 pipe) in C:\Users\lucas\source\repos\SentrySdk\OfficialNet\src\Sentry\Internal\Extensions\JsonExtensions.cs:line 132
   at Sentry.SentryEvent.FromJson(JsonElement json) in C:\Users\lucas\source\repos\SentrySdk\OfficialNet\src\Sentry\SentryEvent.cs:line 382
   at Sentry.Protocol.Envelopes.EnvelopeItem.DeserializePayloadAsync(Stream stream, IReadOnlyDictionary`2 header, CancellationToken cancellationToken) in C:\Users\lucas\source\repos\SentrySdk\OfficialNet\src\Sentry\Envelopes\EnvelopeItem.cs:line 229
   at Sentry.Protocol.Envelopes.EnvelopeItem.DeserializeAsync(Stream stream, CancellationToken cancellationToken) in C:\Users\lucas\source\repos\SentrySdk\OfficialNet\src\Sentry\Envelopes\EnvelopeItem.cs:line 275
   at Sentry.Protocol.Envelopes.Envelope.DeserializeAsync(Stream stream, CancellationToken cancellationToken) in C:\Users\lucas\source\repos\SentrySdk\OfficialNet\src\Sentry\Envelopes\Envelope.cs:line 169
   at Sentry.Internal.Http.CachingTransport.ProcessCacheAsync(CancellationToken cancellationToken) in C:\Users\lucas\source\repos\SentrySdk\OfficialNet\src\Sentry\Internal\Http\CachingTransport.cs:line 173, discarding cached envelope.
```

**Comment by bruno-garcia** [comment]
Agree. We should just have a serialized form of it instead like the `raw_description`, etc.
