### ISSUE TITLE
Serilog not working in dynamically loaded plugin

### ISSUE THREAD

**Issue by Logikgate** [getsentry/sentry-dotnet#959]
### Environment

How do you use Sentry?
I have a plugin that is dynamically loaded via a main application that I do not have control over. In the plugin I use Sentry via Serilog

Which SDK and version?
.Net 4.7
Sentry 3.3.4
Sentry.Serilog 3.3.4

### Steps to Reproduce

Initialize Serilog via

```
loggerConfig.WriteTo.Sentry(o =>
{
    o.Dsn = "dsn";
    o.Release = "version";
    o.MinimumEventLevel = LogEventLevel.Warning;
    o.CacheDirectoryPath = cacheFolder;
    o.Environment = "test";
});

Log.Logger = loggerConfig.createLogger();

Log.Logger.Error("Testing");
     
```

### Expected Result

"Testing" would be sent to Sentry. 

### Actual Result

Nothing happens in Sentry.  The other Serilog sinks I use (RollingFile and AmazonCloudWatch) both work though.  

After setting CachDirectoryPath I do see the folder created and 0kb files created for each log event (screenshot below). Those files stay there until I shut down the main application and then restart it, upon restart those files are deleted but nothing shows up in Sentry.

![image](https://user-images.githubusercontent.com/2379994/116103573-b7d14480-a67d-11eb-9692-16f1ba580d95.png)

**Comment by Logikgate** [comment]
I was able to find this log in the main application's output. Also, was able to reproduce this in a simple project that dynamically loads a class library that depends on Sentry. See here for that project:  https://github.com/Logikgate/sentry-dynamic-error
```
  Error: Error while processing event c8319e1d04bd49fc8d8e1874a8f67ea8: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Threading.Tasks.ValueTask.get_IsCompleted()
   at Sentry.Protocol.Envelopes.Envelope.<SerializeHeaderAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sentry.Protocol.Envelopes.Envelope.<SerializeAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sentry.Internal.Http.CachingTransport.<StoreToCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sentry.Internal.Http.CachingTransport.<SendEnvelopeAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Sentry.Internal.BackgroundWorker.<WorkerAsync>d__19.MoveNext()
```

**Comment by bruno-garcia** [comment]
I couldn't reproduce the `System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral` error you mentioned. But I haven't tried on .NET Framework 4.7 

I tried it on .NET Core 2.1 (the sample in this repo for Serilog) and the problem I see is that you're not flushing the queue at the end of the execution of the program:

<details>
  <summary>SDK output without flush</summary>
```sh
  Debug: Logging enabled with ConsoleDiagnosticLogger and min level: Debug
  Debug: Using 'GzipBufferedRequestBodyHandler' body compression strategy with level Optimal.
  Debug: Flushing existing cache during transport activation up to 00:00:01.
  Debug: Flushing cached envelopes.
  Debug: Flushing cached envelopes.
Warning: Cache directory is empty.
  Debug: No cached file to process.
Warning: Cache directory is empty.
  Debug: No cached file to process.
  Debug: Initializing Hub for Dsn: 'https://eb18e953812b41c3aeb042e666fd3b5c@o447951.ingest.sentry.io/5428537'.
  Debug: Registering integration: 'AppDomainUnhandledExceptionIntegration'.
  Debug: Registering integration: 'AppDomainProcessExitIntegration'.
  Debug: Registering integration: 'TaskUnobservedTaskExceptionIntegration'.
  Debug: New scope pushed.
   Info: Capturing event.
  Debug: Running main event processor on: Event e186836c17ad4759b191de06e9c5aaed
  Debug: No Exception and AttachStacktrace is off. No stack trace will be collected.
  Debug: Envelope queued up.
  Debug: Configuring the scope.
  Debug: Storing file /var/folders/3r/9m5hqv695t97rd0qllgcbyjc0000gn/T/Sentry/132A73C90BBA506000857BC4BFC23E574F1551B5/1619488910_6603_e186836c17ad4759b191de06e9c5aaed_6044116.envelope.
   Info: Disposing the Hub.
Warning: Cache directory is empty.
  Debug: Disposing SentryClient.
  Debug: Disposing BackgroundWorker.
  Debug: Envelope e186836c17ad4759b191de06e9c5aaed handed off to transport. #1 in queue.
  Debug: Flushing cached envelopes.
  Debug: Shutdown scheduled. Stopping by: 00:00:02. #0 in queue.
   Info: Exiting the worker with an empty queue.
  Debug: Reading cached envelope: /var/folders/3r/9m5hqv695t97rd0qllgcbyjc0000gn/T/Sentry/132A73C90BBA506000857BC4BFC23E574F1551B5/__processing/1619488910_6603_e186836c17ad4759b191de06e9c5aaed_6044116.envelope
  Error: Failed to send cached envelope: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Sentry.Internal.Extensions.StreamExtensions.ReadAllBytesAsync(Stream stream, CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Internal/Extensions/StreamExtensions.cs:line 18
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at Sentry.Internal.Extensions.StreamExtensions.ReadAllBytesAsync(Stream stream, CancellationToken cancellationToken)
   at Sentry.Protocol.Envelopes.Envelope.DeserializeHeaderAsync(Stream stream, CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Envelopes/Envelope.cs:line 140
   at Sentry.Protocol.Envelopes.Envelope.DeserializeHeaderAsync(Stream stream, CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Envelopes/Envelope.cs:line 140
   at Sentry.Protocol.Envelopes.Envelope.DeserializeAsync(Stream stream, CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Envelopes/Envelope.cs:line 164
   at Sentry.Internal.Http.CachingTransport.ProcessCacheAsync(CancellationToken cancellationToken) in /Users/bruno/git/sentry-dotnet/src/Sentry/Internal/Http/CachingTransport.cs:line 176, retrying after a delay.
  Debug: Background worker of CachingTransport has shutdown.
  Debug: Disposing scope.
  Debug: Disposing SentryScopeManager.
```
</details>

If I modify it to Flush events at the end:

```
private static async Task Main()
{
    System.Console.WriteLine(System.IO.Path.GetTempPath());
    LoggerConfiguration loggerConfig = new LoggerConfiguration().MinimumLevel.Information();

    loggerConfig.WriteTo.Sentry(o =>
        {
            o.Dsn = "https://eb18e953812b41c3aeb042e666fd3b5c@o447951.ingest.sentry.io/5428537";
            o.Debug = true;
            o.Environment = "test";
            o.CacheDirectoryPath = "/var/folders/3r/9m5hqv695t97rd0qllgcbyjc0000gn/T/";
        });

    Log.Logger = loggerConfig.CreateLogger();

    Log.Logger.Error("error4");

    await SentrySdk.FlushAsync(TimeSpan.FromSeconds(3));
    SentrySdk.Close();
}
```

I Flush it first so that it will asynchronously wait for up to 3 seconds to get events sent, before it closes the SDK.

I see the output:

<details>
  <summary>SDK output without flush</summary>
```sh
➜  Sentry.Samples.Serilog git:(main) ✗ dotnet run
  Debug: Logging enabled with ConsoleDiagnosticLogger and min level: Debug
  Debug: Using 'GzipBufferedRequestBodyHandler' body compression strategy with level Optimal.
  Debug: Flushing existing cache during transport activation up to 00:00:01.
  Debug: Flushing cached envelopes.
  Debug: Flushing cached envelopes.
  Debug: No cached file to process.
  Debug: No cached file to process.
  Debug: Initializing Hub for Dsn: 'https://eb18e953812b41c3aeb042e666fd3b5c@o447951.ingest.sentry.io/5428537'.
  Debug: Registering integration: 'AppDomainUnhandledExceptionIntegration'.
  Debug: Registering integration: 'AppDomainProcessExitIntegration'.
  Debug: Registering integration: 'TaskUnobservedTaskExceptionIntegration'.
  Debug: New scope pushed.
   Info: Capturing event.
  Debug: Running main event processor on: Event e435f36868d84ef1a31dae7dc5e21a37
  Debug: No Exception and AttachStacktrace is off. No stack trace will be collected.
  Debug: Envelope queued up.
  Debug: Configuring the scope.
  Debug: Storing file /var/folders/3r/9m5hqv695t97rd0qllgcbyjc0000gn/T/Sentry/132A73C90BBA506000857BC4BFC23E574F1551B5/1619489140_-9971_e435f36868d84ef1a31dae7dc5e21a37_48209832.envelope.
  Debug: Tracking depth: 1.
  Debug: Envelope e435f36868d84ef1a31dae7dc5e21a37 handed off to transport. #1 in queue.
  Debug: Flushing cached envelopes.
  Debug: Signaling flush completed.
  Debug: Successfully flushed all events up to call to FlushAsync.
   Info: Disposing the Hub.
  Debug: Disposing SentryClient.
  Debug: Disposing BackgroundWorker.
  Debug: Reading cached envelope: /var/folders/3r/9m5hqv695t97rd0qllgcbyjc0000gn/T/Sentry/132A73C90BBA506000857BC4BFC23E574F1551B5/__processing/1619489140_-9971_e435f36868d84ef1a31dae7dc5e21a37_48209832.envelope
  Debug: Sending cached envelope: e435f36868d84ef1a31dae7dc5e21a37
  Debug: Envelope e435f36868d84ef1a31dae7dc5e21a37 successfully received by Sentry.
  Debug: Successfully sent cached envelope: e435f36868d84ef1a31dae7dc5e21a37
  Debug: No cached file to process.
  Debug: Background worker of CachingTransport has shutdown.
  Debug: Disposing scope.
  Debug: Disposing SentryScopeManager.
  Debug: Shutdown scheduled. Stopping by: 00:00:02. #0 in queue.
   Info: Exiting the worker with an empty queue.
```
</details>

Could you please try out with Flush at the end?

**Comment by Logikgate** [comment]
Unfortunately core has an improved way of dependency resolution which is probably why it was not reproducible there.

Calling flush doesn't change the behavior since it throws that exception as soon as the log is sent to serilog.

If you try the sample .Net project above is the error reproducible on your end?

**Comment by bruno-garcia** [comment]
I'll get it on a Windows device and try to repro with .NET Framework. Thanks for the repro

**Comment by bruno-garcia** [comment]
There's some binding redirect problem going on here. [Searching for the error I found this issue on StackExchange.Redis.](https://github.com/StackExchange/StackExchange.Redis/issues/1128)

> Yes, "Unsafe" is one of a known group of libraries with a binding redirect
problem. You can usually fix it by adding manual assembly binding redirects
(Nick has a great post on this here:
https://nickcraver.com/blog/2020/02/11/binding-redirects/), but honestly:
if you want this to go away - move to .NET Core.
>
> I did nerd-snipe David Kean with these issues a while back, and he had an
interest in improving things, but I don't know the state of that. I'll ping
him again.
>
> Marc

More relevant info from that issue:

```
4.5.0 is 4.0.4.0 (!)
4.5.1 is 4.0.4.0 (!)
4.5.2 is 4.0.4.0 (!)
4.5.3 is 4.0.4.1
4.6.0 is 4.0.5.0
4.7.0 is 4.0.6.0
4.7.1 is 4.0.6.1
```

So I installed `System.Runtime.CompilerServices.Unsafe` version 4.5.3 from NuGet and it worked.

It worked [with your current binding redirect](https://github.com/Logikgate/sentry-dynamic-error/blob/master/ClassLibrary1/app.config#L4-L9) and without.

This isnt' a dependency that Sentry takes in directly so not something we can do much. WPF e WinForms are available on .NET Core and you can even publish the runtime with the app (self contained) so the advise is really to move to .NET Core.

I hope this helps.

**Comment by Logikgate** [comment]
Unfortunately, my project is a plugin to an application I have no control over.  So I cannot move to .net Core nor can I install that dependency in the main application.  I guess Sentry just isn't in the cards for that situation.
